import type { FormulaEntry } from "./types";

const v = (symbol: string, name: string, unit?: string) => ({ symbol, name, unit });

/**
 * Extended formula library. Appended to the core FORMULAS list.
 * Operator glyphs here are already display-ready (× ÷ − √ π) and any raw
 * ASCII operators are normalised at render time by formatMath().
 */
export const EXTENDED_FORMULAS: FormulaEntry[] = [
  // ═══ ALGEBRA ══════════════════════════════════════════════════════════════
  { id: "arith_seq", name: "Arithmetic Sequence (nth term)", category: "algebra",
    expression: "aₙ = a₁ + (n − 1)d",
    description: "nth term of an arithmetic progression.",
    variables: [v("a₁","First term"), v("d","Common difference"), v("n","Term index")],
    example: { description: "a₁=3, d=4, n=10", inputs:{a1:3,d:4,n:10}, result:"a₁₀ = 39" },
    keywords: ["arithmetic","sequence","progression","series"] },
  { id: "arith_sum", name: "Arithmetic Series Sum", category: "algebra",
    expression: "Sₙ = n ÷ 2 × (a₁ + aₙ)",
    description: "Sum of the first n terms of an arithmetic series.",
    variables: [v("n","Number of terms"), v("a₁","First term"), v("aₙ","Last term")],
    example: { description: "n=10, a₁=3, aₙ=39", inputs:{n:10,a1:3,an:39}, result:"S = 210" },
    related: ["arith_seq"], keywords: ["sum","series","arithmetic"] },
  { id: "geo_seq", name: "Geometric Sequence (nth term)", category: "algebra",
    expression: "aₙ = a₁ × r^(n−1)",
    description: "nth term of a geometric progression.",
    variables: [v("a₁","First term"), v("r","Common ratio"), v("n","Term index")],
    example: { description: "a₁=2, r=3, n=5", inputs:{a1:2,r:3,n:5}, result:"a₅ = 162" },
    keywords: ["geometric","sequence","ratio"] },
  { id: "geo_sum_inf", name: "Infinite Geometric Sum", category: "algebra",
    expression: "S = a₁ ÷ (1 − r)",
    description: "Sum of an infinite geometric series when |r| < 1.",
    variables: [v("a₁","First term"), v("r","Common ratio")],
    example: { description: "a₁=1, r=0.5", inputs:{a1:1,r:0.5}, result:"S = 2" },
    keywords: ["infinite","series","convergent","geometric"] },
  { id: "binomial", name: "Binomial Theorem", category: "algebra",
    expression: "(a + b)ⁿ = Σ C(n,k) × a^(n−k) × b^k",
    description: "Expansion of a binomial raised to an integer power.",
    variables: [v("n","Exponent"), v("k","Term index")],
    example: { description: "(a+b)³", inputs:{n:3}, result:"a³ + 3a²b + 3ab² + b³" },
    keywords: ["binomial","expansion","combinatorics"] },
  { id: "combinations", name: "Combinations nCr", category: "algebra",
    expression: "C(n,r) = n! ÷ (r! × (n − r)!)",
    description: "Number of ways to choose r items from n without order.",
    variables: [v("n","Total items"), v("r","Chosen items")],
    example: { description: "n=5, r=2", inputs:{n:5,r:2}, result:"C = 10" },
    related: ["permutations"], keywords: ["combination","ncr","choose"], calcLink: "/dashboard/scientific" },
  { id: "permutations", name: "Permutations nPr", category: "algebra",
    expression: "P(n,r) = n! ÷ (n − r)!",
    description: "Number of ordered arrangements of r items from n.",
    variables: [v("n","Total items"), v("r","Chosen items")],
    example: { description: "n=5, r=2", inputs:{n:5,r:2}, result:"P = 20" },
    related: ["combinations"], keywords: ["permutation","npr","arrangement"], calcLink: "/dashboard/scientific" },
  { id: "log_rules", name: "Logarithm Product Rule", category: "algebra",
    expression: "log(a × b) = log a + log b",
    description: "Logarithm of a product equals the sum of the logarithms.",
    variables: [v("a","Value a"), v("b","Value b")],
    example: { description: "log(10×100)", inputs:{a:10,b:100}, result:"= 3" },
    keywords: ["log","logarithm","product","rule"] },
  { id: "change_base", name: "Change of Base", category: "algebra",
    expression: "log_b(x) = ln x ÷ ln b",
    description: "Convert a logarithm from one base to another.",
    variables: [v("x","Value"), v("b","Base")],
    example: { description: "log₂(8)", inputs:{x:8,b:2}, result:"= 3" },
    keywords: ["log","base","convert"] },
  { id: "distance_2d", name: "Distance Between Two Points", category: "algebra",
    expression: "d = √((x₂ − x₁)² + (y₂ − y₁)²)",
    description: "Straight-line distance in the plane.",
    variables: [v("x₁","X of point 1"), v("y₁","Y of point 1"), v("x₂","X of point 2"), v("y₂","Y of point 2")],
    example: { description: "(0,0) to (3,4)", inputs:{x1:0,y1:0,x2:3,y2:4}, result:"d = 5" },
    keywords: ["distance","coordinate","points"], calcLink: "/dashboard/geometry" },
  { id: "slope", name: "Slope of a Line", category: "algebra",
    expression: "m = (y₂ − y₁) ÷ (x₂ − x₁)",
    description: "Gradient between two points.",
    variables: [v("x₁","X1"), v("y₁","Y1"), v("x₂","X2"), v("y₂","Y2")],
    example: { description: "(1,2) to (3,8)", inputs:{x1:1,y1:2,x2:3,y2:8}, result:"m = 3" },
    keywords: ["slope","gradient","line"] },

  // ═══ GEOMETRY ═════════════════════════════════════════════════════════════
  { id: "ellipse_area", name: "Ellipse Area", category: "geometry",
    expression: "A = π × a × b",
    description: "Area of an ellipse from its semi-axes.",
    variables: [v("a","Semi-major axis","mm"), v("b","Semi-minor axis","mm")],
    example: { description: "a=5, b=3", inputs:{a:5,b:3}, result:"A = 47.12" },
    keywords: ["ellipse","oval","area"], calcLink: "/dashboard/geometry" },
  { id: "trapezoid_area", name: "Trapezoid Area", category: "geometry",
    expression: "A = (a + b) ÷ 2 × h",
    description: "Area of a trapezoid.",
    variables: [v("a","Base a","mm"), v("b","Base b","mm"), v("h","Height","mm")],
    example: { description: "a=8, b=4, h=5", inputs:{a:8,b:4,h:5}, result:"A = 30" },
    keywords: ["trapezoid","trapezium","area"], calcLink: "/dashboard/geometry" },
  { id: "reg_poly_area", name: "Regular Polygon Area", category: "geometry",
    expression: "A = (n × s²) ÷ (4 × tan(π ÷ n))",
    description: "Area of a regular n-sided polygon of side s.",
    variables: [v("n","Number of sides"), v("s","Side length","mm")],
    example: { description: "Hexagon s=10", inputs:{n:6,s:10}, result:"A = 259.81" },
    keywords: ["polygon","hexagon","pentagon","area"], calcLink: "/dashboard/geometry" },
  { id: "hex_af", name: "Hexagon Across Flats / Corners", category: "geometry",
    expression: "AF = AC × √3 ÷ 2",
    description: "Relation between across-flats and across-corners of a hexagon.",
    variables: [v("AF","Across flats","mm"), v("AC","Across corners","mm")],
    example: { description: "AC = 20", inputs:{AC:20}, result:"AF = 17.32" },
    keywords: ["hexagon","across flats","bar","hex"], calcLink: "/dashboard/geometry" },
  { id: "cone_vol", name: "Cone Volume", category: "geometry",
    expression: "V = (1 ÷ 3) × π × r² × h",
    description: "Volume of a right circular cone.",
    variables: [v("r","Radius","mm"), v("h","Height","mm")],
    example: { description: "r=3, h=9", inputs:{r:3,h:9}, result:"V = 84.82" },
    keywords: ["cone","volume","taper"], calcLink: "/dashboard/geometry" },
  { id: "cone_slant", name: "Cone Slant Height", category: "geometry",
    expression: "l = √(r² + h²)",
    description: "Slant height of a cone.",
    variables: [v("r","Radius","mm"), v("h","Height","mm")],
    example: { description: "r=3, h=4", inputs:{r:3,h:4}, result:"l = 5" },
    related: ["cone_vol"], keywords: ["cone","slant","height"] },
  { id: "frustum_vol", name: "Frustum Volume", category: "geometry",
    expression: "V = (π × h ÷ 3) × (R² + R × r + r²)",
    description: "Volume of a truncated cone.",
    variables: [v("R","Large radius","mm"), v("r","Small radius","mm"), v("h","Height","mm")],
    example: { description: "R=5, r=3, h=10", inputs:{R:5,r:3,h:10}, result:"V = 513.13" },
    keywords: ["frustum","truncated","cone","volume"], calcLink: "/dashboard/geometry" },
  { id: "torus_vol", name: "Torus Volume", category: "geometry",
    expression: "V = 2 × π² × R × r²",
    description: "Volume of a torus (ring).",
    variables: [v("R","Ring radius","mm"), v("r","Tube radius","mm")],
    example: { description: "R=10, r=2", inputs:{R:10,r:2}, result:"V = 789.57" },
    keywords: ["torus","ring","donut","volume"] },
  { id: "sector_area", name: "Circular Sector Area", category: "geometry",
    expression: "A = (θ ÷ 360) × π × r²",
    description: "Area of a pie slice of a circle.",
    variables: [v("θ","Angle","°"), v("r","Radius","mm")],
    example: { description: "θ=60°, r=10", inputs:{theta:60,r:10}, result:"A = 52.36" },
    keywords: ["sector","arc","slice","area"], calcLink: "/dashboard/geometry" },
  { id: "arc_length", name: "Arc Length", category: "geometry",
    expression: "L = (θ ÷ 360) × 2 × π × r",
    description: "Length of a circular arc.",
    variables: [v("θ","Angle","°"), v("r","Radius","mm")],
    example: { description: "θ=90°, r=10", inputs:{theta:90,r:10}, result:"L = 15.71" },
    keywords: ["arc","length","circle"], calcLink: "/dashboard/geometry" },
  { id: "chord_len", name: "Chord Length", category: "geometry",
    expression: "c = 2 × r × sin(θ ÷ 2)",
    description: "Chord across a circle for a given included angle.",
    variables: [v("r","Radius","mm"), v("θ","Angle","°")],
    example: { description: "r=50, θ=60°", inputs:{r:50,theta:60}, result:"c = 50" },
    keywords: ["chord","circle","bolt circle"], calcLink: "/dashboard/geometry" },
  { id: "bolt_circle", name: "Bolt Circle Coordinates", category: "geometry",
    expression: "x = R × cos(θ), y = R × sin(θ)",
    description: "X/Y position of each hole on a bolt circle.",
    variables: [v("R","Bolt circle radius","mm"), v("θ","Angle","°")],
    example: { description: "R=50, θ=45°", inputs:{R:50,theta:45}, result:"x=35.36, y=35.36" },
    keywords: ["bolt circle","pcd","hole pattern","coordinates"], calcLink: "/dashboard/geometry" },

  // ═══ TRIGONOMETRY ═════════════════════════════════════════════════════════
  { id: "law_sines", name: "Law of Sines", category: "trigonometry",
    expression: "a ÷ sin A = b ÷ sin B = c ÷ sin C",
    description: "Relates sides and opposite angles of any triangle.",
    variables: [v("a","Side a"), v("A","Angle A","°"), v("b","Side b"), v("B","Angle B","°")],
    example: { description: "a=7, A=30°, B=45°", inputs:{a:7,A:30,B:45}, result:"b = 9.90" },
    keywords: ["sine","triangle","oblique","law"] },
  { id: "law_cosines", name: "Law of Cosines", category: "trigonometry",
    expression: "c² = a² + b² − 2ab × cos C",
    description: "Third side of a triangle from two sides and the included angle.",
    variables: [v("a","Side a"), v("b","Side b"), v("C","Included angle","°")],
    example: { description: "a=5, b=7, C=60°", inputs:{a:5,b:7,C:60}, result:"c = 6.24" },
    keywords: ["cosine","triangle","law","sss","sas"] },
  { id: "tri_area_sas", name: "Triangle Area (SAS)", category: "trigonometry",
    expression: "A = ½ × a × b × sin C",
    description: "Area from two sides and the included angle.",
    variables: [v("a","Side a"), v("b","Side b"), v("C","Included angle","°")],
    example: { description: "a=5, b=7, C=60°", inputs:{a:5,b:7,C:60}, result:"A = 15.16" },
    keywords: ["triangle","area","sas","sine"] },
  { id: "heron", name: "Heron's Formula", category: "trigonometry",
    expression: "A = √(s × (s−a) × (s−b) × (s−c)), s = (a+b+c) ÷ 2",
    description: "Triangle area from three sides.",
    variables: [v("a","Side a"), v("b","Side b"), v("c","Side c")],
    example: { description: "3,4,5", inputs:{a:3,b:4,c:5}, result:"A = 6" },
    keywords: ["heron","triangle","area","sss"] },
  { id: "pythag_identity", name: "Pythagorean Identity", category: "trigonometry",
    expression: "sin²θ + cos²θ = 1",
    description: "Fundamental trigonometric identity.",
    variables: [v("θ","Angle","°")],
    example: { description: "θ = 30°", inputs:{theta:30}, result:"0.25 + 0.75 = 1" },
    keywords: ["identity","sin","cos","trig"] },
  { id: "double_angle", name: "Double Angle Formulas", category: "trigonometry",
    expression: "sin 2θ = 2 sinθ cosθ, cos 2θ = cos²θ − sin²θ",
    description: "Trig functions of twice an angle.",
    variables: [v("θ","Angle","°")],
    example: { description: "θ = 30°", inputs:{theta:30}, result:"sin60° = 0.866" },
    keywords: ["double angle","identity","trig"] },
  { id: "taper_angle", name: "Taper Angle", category: "trigonometry",
    expression: "tan(α ÷ 2) = (D − d) ÷ (2 × L)",
    description: "Included taper angle from large and small diameters.",
    variables: [v("D","Large diameter","mm"), v("d","Small diameter","mm"), v("L","Length","mm")],
    example: { description: "D=50, d=40, L=100", inputs:{D:50,d:40,L:100}, result:"α = 5.72°" },
    keywords: ["taper","angle","cone","turning"], calcLink: "/dashboard/machining" },
  { id: "sine_bar", name: "Sine Bar Setup", category: "trigonometry",
    expression: "H = L × sin θ",
    description: "Gauge block stack height for a sine bar angle.",
    variables: [v("L","Sine bar length","mm"), v("θ","Angle","°"), v("H","Stack height","mm")],
    example: { description: "L=100, θ=30°", inputs:{L:100,theta:30}, result:"H = 50 mm" },
    keywords: ["sine bar","inspection","angle","gauge block"] },

  // ═══ CALCULUS ═════════════════════════════════════════════════════════════
  { id: "derivative_def", name: "Derivative (limit definition)", category: "calculus",
    expression: "f′(x) = lim(h→0) (f(x+h) − f(x)) ÷ h",
    description: "Instantaneous rate of change of a function.",
    variables: [v("f","Function"), v("h","Increment")],
    example: { description: "f(x)=x²", inputs:{x:3}, result:"f′(x) = 2x = 6" },
    keywords: ["derivative","limit","slope","calculus"] },
  { id: "power_rule", name: "Power Rule", category: "calculus",
    expression: "d/dx (xⁿ) = n × x^(n−1)",
    description: "Derivative of a power function.",
    variables: [v("n","Exponent")],
    example: { description: "x⁵", inputs:{n:5}, result:"5x⁴" },
    keywords: ["power rule","derivative","differentiation"] },
  { id: "product_rule", name: "Product Rule", category: "calculus",
    expression: "(uv)′ = u′v + uv′",
    description: "Derivative of a product of two functions.",
    variables: [v("u","Function u"), v("v","Function v")],
    example: { description: "x²·sin x", inputs:{}, result:"2x sin x + x² cos x" },
    keywords: ["product rule","derivative"] },
  { id: "quotient_rule", name: "Quotient Rule", category: "calculus",
    expression: "(u ÷ v)′ = (u′v − uv′) ÷ v²",
    description: "Derivative of a quotient of two functions.",
    variables: [v("u","Numerator"), v("v","Denominator")],
    example: { description: "x ÷ (x+1)", inputs:{}, result:"1 ÷ (x+1)²" },
    keywords: ["quotient rule","derivative","division"] },
  { id: "chain_rule", name: "Chain Rule", category: "calculus",
    expression: "d/dx f(g(x)) = f′(g(x)) × g′(x)",
    description: "Derivative of a composite function.",
    variables: [v("f","Outer function"), v("g","Inner function")],
    example: { description: "sin(x²)", inputs:{}, result:"2x cos(x²)" },
    keywords: ["chain rule","composite","derivative"] },
  { id: "power_integral", name: "Power Rule for Integrals", category: "calculus",
    expression: "∫ xⁿ dx = x^(n+1) ÷ (n + 1) + C",
    description: "Antiderivative of a power function (n ≠ −1).",
    variables: [v("n","Exponent")],
    example: { description: "∫x³dx", inputs:{n:3}, result:"x⁴ ÷ 4 + C" },
    keywords: ["integral","antiderivative","power"] },
  { id: "ftc", name: "Fundamental Theorem of Calculus", category: "calculus",
    expression: "∫ₐᵇ f(x) dx = F(b) − F(a)",
    description: "Definite integral evaluated from an antiderivative.",
    variables: [v("a","Lower limit"), v("b","Upper limit")],
    example: { description: "∫₀² x dx", inputs:{a:0,b:2}, result:"= 2" },
    keywords: ["integral","definite","fundamental theorem"] },
  { id: "trapezoid_rule", name: "Trapezoidal Rule", category: "calculus",
    expression: "∫ f dx ≈ (h ÷ 2) × (f₀ + 2f₁ + … + 2fₙ₋₁ + fₙ)",
    description: "Numerical integration by trapezoids.",
    variables: [v("h","Step size"), v("n","Intervals")],
    example: { description: "n=4 strips", inputs:{n:4}, result:"Approximate area" },
    keywords: ["numerical","integration","trapezoid","simpson"] },
  { id: "simpson", name: "Simpson's Rule", category: "calculus",
    expression: "∫ f dx ≈ (h ÷ 3) × (f₀ + 4f₁ + 2f₂ + … + fₙ)",
    description: "Numerical integration using parabolic segments (n even).",
    variables: [v("h","Step size"), v("n","Intervals (even)")],
    example: { description: "n=4 strips", inputs:{n:4}, result:"Higher accuracy than trapezoid" },
    keywords: ["simpson","numerical","integration"] },
  { id: "taylor", name: "Taylor Series", category: "calculus",
    expression: "f(x) = Σ fⁿ(a) ÷ n! × (x − a)ⁿ",
    description: "Power-series expansion of a function about a point.",
    variables: [v("a","Expansion point"), v("n","Term order")],
    example: { description: "eˣ about 0", inputs:{a:0}, result:"1 + x + x²/2 + x³/6 …" },
    keywords: ["taylor","maclaurin","series","expansion"] },

  // ═══ STATISTICS ═══════════════════════════════════════════════════════════
  { id: "variance", name: "Variance (sample)", category: "statistics",
    expression: "s² = Σ(xᵢ − x̄)² ÷ (n − 1)",
    description: "Spread of a sample about its mean.",
    variables: [v("xᵢ","Data value"), v("x̄","Mean"), v("n","Sample size")],
    example: { description: "2,4,4,4,5,5,7,9", inputs:{n:8}, result:"s² = 4.57" },
    keywords: ["variance","spread","sample"], calcLink: "/dashboard/scientific" },
  { id: "std_dev", name: "Standard Deviation", category: "statistics",
    expression: "s = √(Σ(xᵢ − x̄)² ÷ (n − 1))",
    description: "Square root of the variance.",
    variables: [v("xᵢ","Data value"), v("x̄","Mean"), v("n","Sample size")],
    example: { description: "2,4,4,4,5,5,7,9", inputs:{n:8}, result:"s = 2.14" },
    related: ["variance"], keywords: ["standard deviation","sigma","spread"], calcLink: "/dashboard/scientific" },
  { id: "z_score", name: "Z-Score", category: "statistics",
    expression: "z = (x − μ) ÷ σ",
    description: "Number of standard deviations a value sits from the mean.",
    variables: [v("x","Value"), v("μ","Mean"), v("σ","Std deviation")],
    example: { description: "x=70, μ=60, σ=5", inputs:{x:70,mu:60,sigma:5}, result:"z = 2" },
    keywords: ["z score","normal","standardise"] },
  { id: "cp", name: "Process Capability Cp", category: "statistics",
    expression: "Cp = (USL − LSL) ÷ (6σ)",
    description: "Potential capability of a process against its tolerance band.",
    variables: [v("USL","Upper spec limit"), v("LSL","Lower spec limit"), v("σ","Std deviation")],
    example: { description: "USL=10.1, LSL=9.9, σ=0.02", inputs:{USL:10.1,LSL:9.9,sigma:0.02}, result:"Cp = 1.67" },
    notes: "Cp ≥ 1.33 is generally required for a capable process.",
    keywords: ["cp","capability","spc","quality"] },
  { id: "cpk", name: "Process Capability Cpk", category: "statistics",
    expression: "Cpk = min((USL − μ) ÷ 3σ, (μ − LSL) ÷ 3σ)",
    description: "Capability accounting for process centring.",
    variables: [v("USL","Upper spec limit"), v("LSL","Lower spec limit"), v("μ","Mean"), v("σ","Std deviation")],
    example: { description: "μ=10.02, USL=10.1, LSL=9.9, σ=0.02", inputs:{mu:10.02}, result:"Cpk = 1.33" },
    related: ["cp"], keywords: ["cpk","capability","centred","spc"] },
  { id: "linear_reg", name: "Linear Regression Slope", category: "statistics",
    expression: "m = (nΣxy − ΣxΣy) ÷ (nΣx² − (Σx)²)",
    description: "Least-squares best-fit slope.",
    variables: [v("n","Data count"), v("x","X values"), v("y","Y values")],
    example: { description: "Simple trend fit", inputs:{n:5}, result:"m = best-fit slope" },
    keywords: ["regression","least squares","trend","fit"] },
  { id: "std_error", name: "Standard Error of the Mean", category: "statistics",
    expression: "SE = σ ÷ √n",
    description: "Uncertainty of an estimated mean.",
    variables: [v("σ","Std deviation"), v("n","Sample size")],
    example: { description: "σ=2, n=25", inputs:{sigma:2,n:25}, result:"SE = 0.4" },
    keywords: ["standard error","confidence","mean"] },

  // ═══ TURNING / MILLING / DRILLING ═════════════════════════════════════════
  { id: "surface_speed", name: "Surface Speed from RPM", category: "turning",
    expression: "Vc = (π × D × n) ÷ 1000",
    description: "Cutting speed in m/min from diameter and spindle speed.",
    variables: [v("D","Diameter","mm"), v("n","Spindle speed","rpm"), v("Vc","Cutting speed","m/min")],
    example: { description: "D=50, n=1000", inputs:{D:50,n:1000}, result:"Vc = 157.1 m/min" },
    keywords: ["surface speed","sfm","vc","cutting speed"], calcLink: "/dashboard/machining" },
  { id: "turning_mrr", name: "Turning Material Removal Rate", category: "turning",
    expression: "MRR = Vc × aₚ × f",
    description: "Volume of material removed per minute in turning.",
    variables: [v("Vc","Cutting speed","m/min"), v("aₚ","Depth of cut","mm"), v("f","Feed","mm/rev")],
    example: { description: "Vc=200, aₚ=2, f=0.25", inputs:{Vc:200,ap:2,f:0.25}, result:"MRR = 100 cm³/min" },
    keywords: ["mrr","removal rate","turning","productivity"], calcLink: "/dashboard/machining" },
  { id: "turning_time", name: "Turning Cycle Time", category: "turning",
    expression: "T = L ÷ (f × n)",
    description: "Ideal cutting time for one pass along a length.",
    variables: [v("L","Cut length","mm"), v("f","Feed","mm/rev"), v("n","Spindle speed","rpm")],
    example: { description: "L=100, f=0.2, n=1000", inputs:{L:100,f:0.2,n:1000}, result:"T = 0.5 min" },
    notes: "Ideal cutting time only — excludes approach, retract and tool change.",
    keywords: ["cycle time","turning","machining time"], calcLink: "/dashboard/machining" },
  { id: "surface_finish", name: "Theoretical Surface Finish", category: "turning",
    expression: "Ra ≈ (f² ÷ (32 × rε)) × 1000",
    description: "Theoretical roughness from feed and tool nose radius.",
    variables: [v("f","Feed","mm/rev"), v("rε","Nose radius","mm"), v("Ra","Roughness","µm")],
    example: { description: "f=0.2, rε=0.8", inputs:{f:0.2,r:0.8}, result:"Ra ≈ 1.56 µm" },
    keywords: ["surface finish","ra","roughness","nose radius"], calcLink: "/dashboard/machining" },
  { id: "chip_thinning", name: "Radial Chip Thinning Factor", category: "milling",
    expression: "RCTF = √(D ÷ (2 × aₑ)) for aₑ < D ÷ 2",
    description: "Feed compensation factor for light radial engagement.",
    variables: [v("D","Cutter diameter","mm"), v("aₑ","Radial depth","mm")],
    example: { description: "D=12, aₑ=1", inputs:{D:12,ae:1}, result:"RCTF = 2.45" },
    keywords: ["chip thinning","radial","milling","feed"], calcLink: "/dashboard/machining" },
  { id: "milling_mrr", name: "Milling Material Removal Rate", category: "milling",
    expression: "MRR = aₚ × aₑ × vf ÷ 1000",
    description: "Volume removed per minute in milling.",
    variables: [v("aₚ","Axial depth","mm"), v("aₑ","Radial width","mm"), v("vf","Feed rate","mm/min")],
    example: { description: "aₚ=3, aₑ=10, vf=500", inputs:{ap:3,ae:10,vf:500}, result:"MRR = 15 cm³/min" },
    keywords: ["mrr","milling","removal","productivity"], calcLink: "/dashboard/machining" },
  { id: "milling_power", name: "Milling Spindle Power", category: "milling",
    expression: "Pc = (MRR × kc) ÷ (60000 × η)",
    description: "Required spindle power from removal rate and specific cutting force.",
    variables: [v("MRR","Removal rate","cm³/min"), v("kc","Specific cutting force","N/mm²"), v("η","Efficiency")],
    example: { description: "MRR=15, kc=2000, η=0.8", inputs:{MRR:15,kc:2000,eta:0.8}, result:"Pc ≈ 0.63 kW" },
    keywords: ["power","spindle","kw","milling","force"], calcLink: "/dashboard/machining" },
  { id: "chip_load", name: "Chip Load per Tooth", category: "milling",
    expression: "fz = vf ÷ (n × z)",
    description: "Feed per tooth from table feed, rpm and flute count.",
    variables: [v("vf","Feed rate","mm/min"), v("n","Spindle speed","rpm"), v("z","Number of flutes")],
    example: { description: "vf=600, n=2000, z=4", inputs:{vf:600,n:2000,z:4}, result:"fz = 0.075 mm" },
    notes: "Flute count must be a positive whole number.",
    keywords: ["chip load","feed per tooth","fz","flutes"], calcLink: "/dashboard/machining" },
  { id: "milling_engage", name: "Cutter Engagement Angle", category: "milling",
    expression: "θ = arccos(1 − (2 × aₑ ÷ D))",
    description: "Angle of cut engagement for a given radial width.",
    variables: [v("aₑ","Radial depth","mm"), v("D","Cutter diameter","mm")],
    example: { description: "aₑ=3, D=12", inputs:{ae:3,D:12}, result:"θ = 60°" },
    keywords: ["engagement","arc of contact","milling"], calcLink: "/dashboard/machining" },
  { id: "drill_point_len", name: "Drill Point Length", category: "drilling",
    expression: "Lₚ = (D ÷ 2) ÷ tan(σ ÷ 2)",
    description: "Axial length of the drill point cone.",
    variables: [v("D","Drill diameter","mm"), v("σ","Point angle","°")],
    example: { description: "D=10, σ=118°", inputs:{D:10,sigma:118}, result:"Lₚ = 3.0 mm" },
    notes: "Add this to the hole depth when calculating breakthrough time.",
    keywords: ["drill point","118","135","point angle"], calcLink: "/dashboard/machining" },
  { id: "drill_time", name: "Drilling Cutting Time", category: "drilling",
    expression: "T = (L + Lₚ + Lₐ) ÷ (f × n)",
    description: "Ideal drilling time including point and approach allowances.",
    variables: [v("L","Hole depth","mm"), v("Lₚ","Point length","mm"), v("Lₐ","Approach","mm"), v("f","Feed","mm/rev"), v("n","Speed","rpm")],
    example: { description: "L=30, Lₚ=3, Lₐ=2, f=0.15, n=1200", inputs:{L:30,f:0.15,n:1200}, result:"T ≈ 0.19 min" },
    notes: "Ideal cutting time — peck retracts and dwell are not included.",
    related: ["drill_point_len"], keywords: ["drilling","time","peck","cycle"], calcLink: "/dashboard/machining" },
  { id: "drill_thrust", name: "Drilling Thrust Force", category: "drilling",
    expression: "Ff ≈ 0.5 × kc × D × f ÷ 2",
    description: "Approximate axial thrust required to drill.",
    variables: [v("kc","Specific cutting force","N/mm²"), v("D","Diameter","mm"), v("f","Feed","mm/rev")],
    example: { description: "kc=2000, D=10, f=0.15", inputs:{kc:2000,D:10,f:0.15}, result:"Ff ≈ 750 N" },
    keywords: ["thrust","force","drilling","axial"] },
  { id: "tap_drill", name: "Tap Drill Size (metric)", category: "threading",
    expression: "d = D − P",
    description: "Tapping drill diameter for a metric coarse thread (75% engagement).",
    variables: [v("D","Nominal diameter","mm"), v("P","Pitch","mm")],
    example: { description: "M10 × 1.5", inputs:{D:10,P:1.5}, result:"d = 8.5 mm" },
    keywords: ["tap drill","metric","thread","pitch"], calcLink: "/dashboard/machining" },
  { id: "thread_pitch_dia", name: "Metric Thread Pitch Diameter", category: "threading",
    expression: "d₂ = D − 0.6495 × P",
    description: "Pitch diameter of an ISO metric thread.",
    variables: [v("D","Major diameter","mm"), v("P","Pitch","mm")],
    example: { description: "M10 × 1.5", inputs:{D:10,P:1.5}, result:"d₂ = 9.026 mm" },
    keywords: ["pitch diameter","thread","iso","metric"], calcLink: "/dashboard/machining" },
  { id: "thread_engagement", name: "Thread Percentage of Engagement", category: "threading",
    expression: "E = ((D − d) ÷ (1.0825 × P)) × 100",
    description: "Percent thread engagement for a chosen tap drill.",
    variables: [v("D","Major diameter","mm"), v("d","Drill diameter","mm"), v("P","Pitch","mm")],
    example: { description: "M10×1.5, drill 8.5", inputs:{D:10,d:8.5,P:1.5}, result:"E ≈ 92%" },
    keywords: ["engagement","thread","tap","percent"] },
  { id: "thread_torque", name: "Bolt Tightening Torque", category: "threading",
    expression: "T = K × F × d ÷ 1000",
    description: "Torque required for a target bolt preload.",
    variables: [v("K","Nut factor"), v("F","Preload","N"), v("d","Nominal diameter","mm")],
    example: { description: "K=0.2, F=20000, d=10", inputs:{K:0.2,F:20000,d:10}, result:"T = 40 N·m" },
    notes: "K ≈ 0.2 dry, 0.15 lubricated. Always confirm against the joint spec.",
    keywords: ["torque","bolt","preload","tightening"] },

  // ═══ SHEET METAL / WELDING / GEARS ════════════════════════════════════════
  { id: "bend_allowance", name: "Bend Allowance", category: "sheet_metal",
    expression: "BA = (π ÷ 180) × A × (R + K × T)",
    description: "Flat-length allowance consumed by a sheet metal bend.",
    variables: [v("A","Bend angle","°"), v("R","Inside radius","mm"), v("K","K-factor"), v("T","Thickness","mm")],
    example: { description: "A=90, R=2, T=2, K=0.44", inputs:{A:90,R:2,T:2,K:0.44}, result:"BA = 4.52 mm" },
    keywords: ["bend allowance","sheet metal","k-factor","flat pattern"] },
  { id: "bend_deduction", name: "Bend Deduction", category: "sheet_metal",
    expression: "BD = 2 × OSSB − BA",
    description: "Amount subtracted from the outside dimensions for a flat pattern.",
    variables: [v("OSSB","Outside setback","mm"), v("BA","Bend allowance","mm")],
    example: { description: "OSSB=4, BA=4.52", inputs:{OSSB:4,BA:4.52}, result:"BD = 3.48 mm" },
    related: ["bend_allowance"], keywords: ["bend deduction","flat pattern","sheet metal"] },
  { id: "press_force", name: "Press Brake Bending Force", category: "sheet_metal",
    expression: "F = (650 × T² × L) ÷ (V × 1000)",
    description: "Approximate air-bending tonnage for mild steel.",
    variables: [v("T","Thickness","mm"), v("L","Bend length","mm"), v("V","Die opening","mm")],
    example: { description: "T=3, L=1000, V=24", inputs:{T:3,L:1000,V:24}, result:"F ≈ 244 kN" },
    notes: "Mild steel ≈ 450 MPa tensile. Scale for other materials.",
    keywords: ["press brake","tonnage","bending force","air bend"] },
  { id: "shear_force", name: "Shearing Force", category: "sheet_metal",
    expression: "F = L × T × τ",
    description: "Force required to shear a sheet.",
    variables: [v("L","Cut length","mm"), v("T","Thickness","mm"), v("τ","Shear strength","MPa")],
    example: { description: "L=500, T=2, τ=310", inputs:{L:500,T:2,tau:310}, result:"F = 310 kN" },
    keywords: ["shear","punch","blank","force"] },
  { id: "weld_throat", name: "Fillet Weld Throat", category: "welding",
    expression: "a = z × 0.707",
    description: "Design throat thickness of an equal-leg fillet weld.",
    variables: [v("z","Leg length","mm"), v("a","Throat","mm")],
    example: { description: "z=6", inputs:{z:6}, result:"a = 4.24 mm" },
    keywords: ["weld","fillet","throat","leg"] },
  { id: "weld_strength", name: "Fillet Weld Strength", category: "welding",
    expression: "F = a × L × τ",
    description: "Capacity of a fillet weld from throat, length and allowable stress.",
    variables: [v("a","Throat","mm"), v("L","Weld length","mm"), v("τ","Allowable shear","MPa")],
    example: { description: "a=4.24, L=100, τ=140", inputs:{a:4.24,L:100,tau:140}, result:"F ≈ 59.4 kN" },
    related: ["weld_throat"], keywords: ["weld","strength","fillet","capacity"] },
  { id: "weld_heat_input", name: "Welding Heat Input", category: "welding",
    expression: "HI = (V × I × 60) ÷ (v × 1000)",
    description: "Heat input per unit length of weld.",
    variables: [v("V","Arc voltage","V"), v("I","Current","A"), v("v","Travel speed","mm/min")],
    example: { description: "V=25, I=200, v=300", inputs:{V:25,I:200,v:300}, result:"HI = 1.0 kJ/mm" },
    keywords: ["heat input","welding","arc","travel speed"] },
  { id: "gear_module", name: "Gear Module", category: "gears",
    expression: "m = d ÷ z",
    description: "Module from pitch diameter and tooth count.",
    variables: [v("d","Pitch diameter","mm"), v("z","Number of teeth")],
    example: { description: "d=60, z=30", inputs:{d:60,z:30}, result:"m = 2" },
    keywords: ["gear","module","pitch","teeth"] },
  { id: "gear_od", name: "Gear Outside Diameter", category: "gears",
    expression: "Dₒ = m × (z + 2)",
    description: "Blank outside diameter for a spur gear.",
    variables: [v("m","Module","mm"), v("z","Number of teeth")],
    example: { description: "m=2, z=30", inputs:{m:2,z:30}, result:"Dₒ = 64 mm" },
    related: ["gear_module"], keywords: ["gear","outside diameter","blank"] },
  { id: "gear_ratio", name: "Gear Ratio", category: "gears",
    expression: "i = z₂ ÷ z₁ = n₁ ÷ n₂",
    description: "Speed and torque ratio of a gear pair.",
    variables: [v("z₁","Driver teeth"), v("z₂","Driven teeth"), v("n","Speed","rpm")],
    example: { description: "z₁=20, z₂=60", inputs:{z1:20,z2:60}, result:"i = 3:1" },
    keywords: ["gear ratio","reduction","drive","teeth"] },
  { id: "belt_length", name: "V-Belt Length", category: "gears",
    expression: "L = 2C + (π ÷ 2)(D + d) + (D − d)² ÷ (4C)",
    description: "Pitch length of an open belt drive.",
    variables: [v("C","Centre distance","mm"), v("D","Large pulley","mm"), v("d","Small pulley","mm")],
    example: { description: "C=500, D=200, d=100", inputs:{C:500,D:200,d:100}, result:"L ≈ 1476 mm" },
    keywords: ["belt","pulley","drive","length"] },

  // ═══ GD&T / METROLOGY ═════════════════════════════════════════════════════
  { id: "bilateral_tol", name: "Bilateral Tolerance Limits", category: "gdt",
    expression: "Limits = N ± t",
    description: "Upper and lower limits of a bilaterally toleranced dimension.",
    variables: [v("N","Nominal","mm"), v("t","Tolerance","mm")],
    example: { description: "25 ± 0.05", inputs:{N:25,t:0.05}, result:"24.95 – 25.05" },
    keywords: ["tolerance","limits","bilateral"], calcLink: "/dashboard/tolerances" },
  { id: "fit_clearance", name: "Clearance Fit Allowance", category: "gdt",
    expression: "Cmax = Dmax − dmin, Cmin = Dmin − dmax",
    description: "Maximum and minimum clearance of a shaft/hole fit.",
    variables: [v("D","Hole size","mm"), v("d","Shaft size","mm")],
    example: { description: "H7/g6 Ø25", inputs:{D:25}, result:"Cmin 0.007, Cmax 0.041" },
    keywords: ["fit","clearance","iso","h7","shaft","hole"], calcLink: "/dashboard/tolerances" },
  { id: "mmc_bonus", name: "MMC Bonus Tolerance", category: "gdt",
    expression: "Bonus = |Actual size − MMC size|",
    description: "Additional positional tolerance gained when departing from MMC.",
    variables: [v("MMC","Maximum material condition","mm"), v("Actual","Measured size","mm")],
    example: { description: "MMC 10.0, actual 10.1 hole", inputs:{MMC:10,Actual:10.1}, result:"Bonus = 0.1 mm" },
    keywords: ["mmc","bonus","gd&t","position"], calcLink: "/dashboard/tolerances" },
  { id: "true_position", name: "True Position Deviation", category: "gdt",
    expression: "TP = 2 × √(Δx² + Δy²)",
    description: "Diametral positional deviation of a feature.",
    variables: [v("Δx","X deviation","mm"), v("Δy","Y deviation","mm")],
    example: { description: "Δx=0.03, Δy=0.04", inputs:{dx:0.03,dy:0.04}, result:"TP = 0.1 mm" },
    keywords: ["true position","gd&t","location","deviation"], calcLink: "/dashboard/tolerances" },
  { id: "stackup_rss", name: "RSS Tolerance Stack-Up", category: "gdt",
    expression: "T = √(t₁² + t₂² + … + tₙ²)",
    description: "Statistical (root-sum-square) tolerance stack.",
    variables: [v("tᵢ","Individual tolerance","mm")],
    example: { description: "0.1, 0.1, 0.1", inputs:{n:3}, result:"T = 0.173 mm" },
    keywords: ["stack up","rss","tolerance","statistical"], calcLink: "/dashboard/tolerances" },

  // ═══ MECHANICS ════════════════════════════════════════════════════════════
  { id: "stress_normal", name: "Normal Stress", category: "mechanics",
    expression: "σ = F ÷ A",
    description: "Direct stress from axial load.",
    variables: [v("F","Force","N"), v("A","Area","mm²"), v("σ","Stress","MPa")],
    example: { description: "F=10000, A=100", inputs:{F:10000,A:100}, result:"σ = 100 MPa" },
    keywords: ["stress","axial","tension","compression"] },
  { id: "strain", name: "Engineering Strain", category: "mechanics",
    expression: "ε = ΔL ÷ L₀",
    description: "Relative deformation under load.",
    variables: [v("ΔL","Change in length","mm"), v("L₀","Original length","mm")],
    example: { description: "ΔL=0.5, L₀=1000", inputs:{dL:0.5,L0:1000}, result:"ε = 0.0005" },
    keywords: ["strain","deformation","elongation"] },
  { id: "hooke", name: "Hooke's Law", category: "mechanics",
    expression: "σ = E × ε",
    description: "Linear elastic relation between stress and strain.",
    variables: [v("E","Young's modulus","MPa"), v("ε","Strain")],
    example: { description: "E=210000, ε=0.0005", inputs:{E:210000,eps:0.0005}, result:"σ = 105 MPa" },
    related: ["strain","stress_normal"], keywords: ["hooke","elastic","modulus","young"] },
  { id: "bending_stress", name: "Bending Stress", category: "mechanics",
    expression: "σ = M × c ÷ I",
    description: "Maximum bending stress in a beam section.",
    variables: [v("M","Bending moment","N·mm"), v("c","Distance to fibre","mm"), v("I","Second moment of area","mm⁴")],
    example: { description: "M=1e6, c=25, I=520833", inputs:{M:1000000,c:25,I:520833}, result:"σ = 48 MPa" },
    keywords: ["bending","beam","stress","moment"] },
  { id: "second_moment_rect", name: "Second Moment of Area (rectangle)", category: "mechanics",
    expression: "I = b × h³ ÷ 12",
    description: "Area moment of inertia of a rectangular section.",
    variables: [v("b","Width","mm"), v("h","Height","mm")],
    example: { description: "b=50, h=50", inputs:{b:50,h:50}, result:"I = 520833 mm⁴" },
    keywords: ["inertia","second moment","section","rectangle"] },
  { id: "second_moment_circ", name: "Second Moment of Area (circle)", category: "mechanics",
    expression: "I = π × d⁴ ÷ 64",
    description: "Area moment of inertia of a solid round section.",
    variables: [v("d","Diameter","mm")],
    example: { description: "d=50", inputs:{d:50}, result:"I = 306796 mm⁴" },
    keywords: ["inertia","circle","shaft","section"] },
  { id: "torsion_stress", name: "Torsional Shear Stress", category: "mechanics",
    expression: "τ = T × r ÷ J",
    description: "Shear stress in a shaft under torque.",
    variables: [v("T","Torque","N·mm"), v("r","Radius","mm"), v("J","Polar moment","mm⁴")],
    example: { description: "T=500000, r=25, J=613592", inputs:{T:500000,r:25,J:613592}, result:"τ = 20.4 MPa" },
    keywords: ["torsion","shaft","shear","torque"] },
  { id: "beam_defl_simple", name: "Simply Supported Beam Deflection", category: "mechanics",
    expression: "δ = (5 × w × L⁴) ÷ (384 × E × I)",
    description: "Mid-span deflection under a uniform load.",
    variables: [v("w","Load","N/mm"), v("L","Span","mm"), v("E","Modulus","MPa"), v("I","Inertia","mm⁴")],
    example: { description: "w=10, L=1000, E=210000, I=520833", inputs:{w:10,L:1000}, result:"δ = 1.19 mm" },
    keywords: ["deflection","beam","udl","simply supported"] },
  { id: "beam_defl_cant", name: "Cantilever Beam Deflection", category: "mechanics",
    expression: "δ = (F × L³) ÷ (3 × E × I)",
    description: "Tip deflection of a cantilever with an end load.",
    variables: [v("F","Load","N"), v("L","Length","mm"), v("E","Modulus","MPa"), v("I","Inertia","mm⁴")],
    example: { description: "F=1000, L=500, E=210000, I=520833", inputs:{F:1000,L:500}, result:"δ = 0.38 mm" },
    keywords: ["cantilever","deflection","beam","tip load"] },
  { id: "buckling", name: "Euler Buckling Load", category: "mechanics",
    expression: "Pcr = (π² × E × I) ÷ (K × L)²",
    description: "Critical buckling load of a slender column.",
    variables: [v("E","Modulus","MPa"), v("I","Inertia","mm⁴"), v("K","Effective length factor"), v("L","Length","mm")],
    example: { description: "E=210000, I=5000, L=1000, K=1", inputs:{E:210000,I:5000,L:1000,K:1}, result:"Pcr ≈ 10.4 kN" },
    keywords: ["buckling","euler","column","critical load"] },
  { id: "safety_factor", name: "Factor of Safety", category: "mechanics",
    expression: "FoS = σ_yield ÷ σ_working",
    description: "Ratio of material strength to applied stress.",
    variables: [v("σ_yield","Yield strength","MPa"), v("σ_working","Working stress","MPa")],
    example: { description: "250 / 100", inputs:{y:250,w:100}, result:"FoS = 2.5" },
    keywords: ["safety factor","fos","design","yield"] },
  { id: "spring_rate", name: "Helical Spring Rate", category: "mechanics",
    expression: "k = (G × d⁴) ÷ (8 × D³ × n)",
    description: "Stiffness of a helical compression spring.",
    variables: [v("G","Shear modulus","MPa"), v("d","Wire diameter","mm"), v("D","Mean coil diameter","mm"), v("n","Active coils")],
    example: { description: "G=79000, d=2, D=15, n=10", inputs:{G:79000,d:2,D:15,n:10}, result:"k ≈ 4.68 N/mm" },
    keywords: ["spring","rate","stiffness","helical"] },

  // ═══ PHYSICS ══════════════════════════════════════════════════════════════
  { id: "newton2", name: "Newton's Second Law", category: "physics",
    expression: "F = m × a",
    description: "Force equals mass times acceleration.",
    variables: [v("m","Mass","kg"), v("a","Acceleration","m/s²")],
    example: { description: "m=10, a=9.81", inputs:{m:10,a:9.81}, result:"F = 98.1 N" },
    keywords: ["newton","force","mass","acceleration"] },
  { id: "work", name: "Work Done", category: "physics",
    expression: "W = F × d × cos θ",
    description: "Work done by a force through a displacement.",
    variables: [v("F","Force","N"), v("d","Distance","m"), v("θ","Angle","°")],
    example: { description: "F=100, d=5, θ=0", inputs:{F:100,d:5}, result:"W = 500 J" },
    keywords: ["work","energy","joule","force"] },
  { id: "power_mech", name: "Mechanical Power", category: "physics",
    expression: "P = W ÷ t = F × v",
    description: "Rate of doing work.",
    variables: [v("W","Work","J"), v("t","Time","s"), v("F","Force","N"), v("v","Velocity","m/s")],
    example: { description: "W=500, t=10", inputs:{W:500,t:10}, result:"P = 50 W" },
    keywords: ["power","watt","work","rate"] },
  { id: "kinetic_energy", name: "Kinetic Energy", category: "physics",
    expression: "KE = ½ × m × v²",
    description: "Energy of a moving mass.",
    variables: [v("m","Mass","kg"), v("v","Velocity","m/s")],
    example: { description: "m=2, v=10", inputs:{m:2,v:10}, result:"KE = 100 J" },
    keywords: ["kinetic","energy","motion"] },
  { id: "potential_energy", name: "Gravitational Potential Energy", category: "physics",
    expression: "PE = m × g × h",
    description: "Energy stored by height in a gravity field.",
    variables: [v("m","Mass","kg"), v("g","Gravity","m/s²"), v("h","Height","m")],
    example: { description: "m=2, h=10", inputs:{m:2,g:9.81,h:10}, result:"PE = 196.2 J" },
    keywords: ["potential","energy","gravity","height"] },
  { id: "momentum", name: "Linear Momentum", category: "physics",
    expression: "p = m × v",
    description: "Momentum of a moving body.",
    variables: [v("m","Mass","kg"), v("v","Velocity","m/s")],
    example: { description: "m=5, v=4", inputs:{m:5,v:4}, result:"p = 20 kg·m/s" },
    keywords: ["momentum","impulse","mass","velocity"] },
  { id: "torque_phys", name: "Torque", category: "physics",
    expression: "τ = F × r × sin θ",
    description: "Moment of a force about a point.",
    variables: [v("F","Force","N"), v("r","Lever arm","m"), v("θ","Angle","°")],
    example: { description: "F=100, r=0.5, θ=90°", inputs:{F:100,r:0.5}, result:"τ = 50 N·m" },
    keywords: ["torque","moment","lever"] },
  { id: "rot_power", name: "Power from Torque and Speed", category: "physics",
    expression: "P = (2 × π × n × τ) ÷ 60000",
    description: "Shaft power from torque and rotational speed.",
    variables: [v("n","Speed","rpm"), v("τ","Torque","N·m")],
    example: { description: "n=1500, τ=50", inputs:{n:1500,tau:50}, result:"P = 7.85 kW" },
    keywords: ["power","torque","rpm","shaft","motor"] },
  { id: "suvat", name: "Kinematic Equation", category: "physics",
    expression: "v² = u² + 2 × a × s",
    description: "Velocity after accelerating over a distance.",
    variables: [v("u","Initial velocity","m/s"), v("a","Acceleration","m/s²"), v("s","Distance","m")],
    example: { description: "u=0, a=2, s=25", inputs:{u:0,a:2,s:25}, result:"v = 10 m/s" },
    keywords: ["kinematics","suvat","motion","acceleration"] },
  { id: "friction", name: "Frictional Force", category: "physics",
    expression: "Ff = μ × N",
    description: "Friction force from the normal load.",
    variables: [v("μ","Coefficient of friction"), v("N","Normal force","N")],
    example: { description: "μ=0.3, N=500", inputs:{mu:0.3,N:500}, result:"Ff = 150 N" },
    keywords: ["friction","coefficient","normal force"] },
  { id: "pressure", name: "Pressure", category: "physics",
    expression: "P = F ÷ A",
    description: "Force distributed over an area.",
    variables: [v("F","Force","N"), v("A","Area","m²")],
    example: { description: "F=1000, A=0.01", inputs:{F:1000,A:0.01}, result:"P = 100 kPa" },
    keywords: ["pressure","force","area","pascal"] },
  { id: "density", name: "Density", category: "physics",
    expression: "ρ = m ÷ V",
    description: "Mass per unit volume.",
    variables: [v("m","Mass","kg"), v("V","Volume","m³")],
    example: { description: "m=7.85, V=0.001", inputs:{m:7.85,V:0.001}, result:"ρ = 7850 kg/m³" },
    keywords: ["density","mass","volume"], calcLink: "/dashboard/weight" },

  // ═══ ELECTRICAL ═══════════════════════════════════════════════════════════
  { id: "ohms_law", name: "Ohm's Law", category: "electrical",
    expression: "V = I × R",
    description: "Voltage across a resistance carrying a current.",
    variables: [v("V","Voltage","V"), v("I","Current","A"), v("R","Resistance","Ω")],
    example: { description: "I=2, R=10", inputs:{I:2,R:10}, result:"V = 20 V" },
    keywords: ["ohm","voltage","current","resistance"] },
  { id: "elec_power", name: "Electrical Power", category: "electrical",
    expression: "P = V × I = I² × R",
    description: "Power dissipated in a circuit element.",
    variables: [v("V","Voltage","V"), v("I","Current","A"), v("R","Resistance","Ω")],
    example: { description: "V=230, I=5", inputs:{V:230,I:5}, result:"P = 1150 W" },
    keywords: ["power","watt","electrical"] },
  { id: "three_phase_power", name: "Three-Phase Power", category: "electrical",
    expression: "P = √3 × V × I × cos φ",
    description: "Real power of a balanced three-phase load.",
    variables: [v("V","Line voltage","V"), v("I","Line current","A"), v("cos φ","Power factor")],
    example: { description: "V=400, I=10, PF=0.85", inputs:{V:400,I:10,pf:0.85}, result:"P ≈ 5.89 kW" },
    keywords: ["three phase","power factor","motor","kw"] },
  { id: "motor_current", name: "Motor Full-Load Current", category: "electrical",
    expression: "I = (P × 1000) ÷ (√3 × V × cos φ × η)",
    description: "Approximate full-load current of a 3-phase motor.",
    variables: [v("P","Power","kW"), v("V","Voltage","V"), v("cos φ","Power factor"), v("η","Efficiency")],
    example: { description: "P=7.5, V=400, PF=0.85, η=0.9", inputs:{P:7.5}, result:"I ≈ 14.2 A" },
    keywords: ["motor","current","fla","amps"] },
  { id: "res_series", name: "Resistors in Series", category: "electrical",
    expression: "Rₜ = R₁ + R₂ + … + Rₙ",
    description: "Total resistance of series resistors.",
    variables: [v("Rᵢ","Resistance","Ω")],
    example: { description: "10 + 20 + 30", inputs:{n:3}, result:"Rₜ = 60 Ω" },
    keywords: ["series","resistance","circuit"] },
  { id: "res_parallel", name: "Resistors in Parallel", category: "electrical",
    expression: "1 ÷ Rₜ = 1 ÷ R₁ + 1 ÷ R₂ + …",
    description: "Total resistance of parallel resistors.",
    variables: [v("Rᵢ","Resistance","Ω")],
    example: { description: "10 ∥ 10", inputs:{R1:10,R2:10}, result:"Rₜ = 5 Ω" },
    keywords: ["parallel","resistance","circuit"] },
  { id: "cap_reactance", name: "Capacitive Reactance", category: "electrical",
    expression: "Xc = 1 ÷ (2 × π × f × C)",
    description: "Opposition of a capacitor to AC.",
    variables: [v("f","Frequency","Hz"), v("C","Capacitance","F")],
    example: { description: "f=50, C=100µF", inputs:{f:50,C:0.0001}, result:"Xc ≈ 31.8 Ω" },
    keywords: ["reactance","capacitor","ac","impedance"] },
  { id: "ind_reactance", name: "Inductive Reactance", category: "electrical",
    expression: "Xl = 2 × π × f × L",
    description: "Opposition of an inductor to AC.",
    variables: [v("f","Frequency","Hz"), v("L","Inductance","H")],
    example: { description: "f=50, L=0.1", inputs:{f:50,L:0.1}, result:"Xl ≈ 31.4 Ω" },
    keywords: ["reactance","inductor","ac","impedance"] },
  { id: "wire_resistance", name: "Conductor Resistance", category: "electrical",
    expression: "R = ρ × L ÷ A",
    description: "Resistance of a wire from resistivity, length and area.",
    variables: [v("ρ","Resistivity","Ω·m"), v("L","Length","m"), v("A","Area","m²")],
    example: { description: "Copper 10 m, 2.5 mm²", inputs:{L:10,A:0.0000025}, result:"R ≈ 0.069 Ω" },
    keywords: ["wire","resistance","cable","voltage drop"] },
  { id: "voltage_divider", name: "Voltage Divider", category: "electrical",
    expression: "Vout = Vin × R₂ ÷ (R₁ + R₂)",
    description: "Output of a two-resistor divider.",
    variables: [v("Vin","Input voltage","V"), v("R₁","Resistor 1","Ω"), v("R₂","Resistor 2","Ω")],
    example: { description: "12 V, 1k / 1k", inputs:{Vin:12,R1:1000,R2:1000}, result:"Vout = 6 V" },
    keywords: ["divider","voltage","resistor"] },

  // ═══ THERMAL ══════════════════════════════════════════════════════════════
  { id: "thermal_expansion", name: "Linear Thermal Expansion", category: "thermal",
    expression: "ΔL = α × L₀ × ΔT",
    description: "Length change of a part with temperature.",
    variables: [v("α","Expansion coefficient","1/°C"), v("L₀","Original length","mm"), v("ΔT","Temp change","°C")],
    example: { description: "Steel 1000 mm, +50 °C", inputs:{alpha:0.000012,L0:1000,dT:50}, result:"ΔL = 0.6 mm" },
    keywords: ["expansion","thermal","temperature","growth"] },
  { id: "heat_capacity", name: "Sensible Heat", category: "thermal",
    expression: "Q = m × c × ΔT",
    description: "Heat needed to change a material's temperature.",
    variables: [v("m","Mass","kg"), v("c","Specific heat","J/kg·K"), v("ΔT","Temp change","K")],
    example: { description: "1 kg steel, +100 K", inputs:{m:1,c:490,dT:100}, result:"Q = 49 kJ" },
    keywords: ["heat","specific heat","energy","temperature"] },
  { id: "conduction", name: "Fourier Heat Conduction", category: "thermal",
    expression: "Q = (k × A × ΔT) ÷ L",
    description: "Steady-state conduction through a wall.",
    variables: [v("k","Conductivity","W/m·K"), v("A","Area","m²"), v("ΔT","Temp difference","K"), v("L","Thickness","m")],
    example: { description: "k=50, A=1, ΔT=100, L=0.01", inputs:{k:50,A:1,dT:100,L:0.01}, result:"Q = 500 kW" },
    keywords: ["conduction","fourier","heat transfer"] },
  { id: "convection", name: "Newton's Law of Cooling", category: "thermal",
    expression: "Q = h × A × (Ts − T∞)",
    description: "Convective heat transfer from a surface.",
    variables: [v("h","Coefficient","W/m²·K"), v("A","Area","m²"), v("Ts","Surface temp","°C"), v("T∞","Fluid temp","°C")],
    example: { description: "h=25, A=2, ΔT=60", inputs:{h:25,A:2,dT:60}, result:"Q = 3 kW" },
    keywords: ["convection","cooling","heat transfer"] },
  { id: "temp_convert", name: "Celsius ↔ Fahrenheit", category: "thermal",
    expression: "°F = °C × 9 ÷ 5 + 32",
    description: "Temperature scale conversion.",
    variables: [v("°C","Celsius"), v("°F","Fahrenheit")],
    example: { description: "100 °C", inputs:{C:100}, result:"212 °F" },
    keywords: ["temperature","celsius","fahrenheit","convert"], calcLink: "/dashboard/converter" },

  // ═══ FLUIDS ═══════════════════════════════════════════════════════════════
  { id: "darcy", name: "Darcy–Weisbach Head Loss", category: "fluid",
    expression: "hf = f × (L ÷ D) × (v² ÷ (2g))",
    description: "Friction head loss in a pipe.",
    variables: [v("f","Friction factor"), v("L","Length","m"), v("D","Diameter","m"), v("v","Velocity","m/s")],
    example: { description: "f=0.02, L=100, D=0.1, v=2", inputs:{f:0.02,L:100,D:0.1,v:2}, result:"hf ≈ 4.08 m" },
    keywords: ["head loss","darcy","friction","pipe"] },
  { id: "pump_power", name: "Pump Hydraulic Power", category: "fluid",
    expression: "P = (ρ × g × Q × H) ÷ (1000 × η)",
    description: "Shaft power needed by a pump.",
    variables: [v("ρ","Density","kg/m³"), v("Q","Flow","m³/s"), v("H","Head","m"), v("η","Efficiency")],
    example: { description: "Q=0.01, H=20, η=0.7", inputs:{Q:0.01,H:20,eta:0.7}, result:"P ≈ 2.8 kW" },
    keywords: ["pump","power","head","flow"] },
  { id: "continuity", name: "Continuity Equation", category: "fluid",
    expression: "A₁ × v₁ = A₂ × v₂",
    description: "Conservation of mass in incompressible flow.",
    variables: [v("A","Area","m²"), v("v","Velocity","m/s")],
    example: { description: "A₁=0.01, v₁=2, A₂=0.005", inputs:{A1:0.01,v1:2,A2:0.005}, result:"v₂ = 4 m/s" },
    keywords: ["continuity","flow","velocity","area"] },
  { id: "hyd_cyl_force", name: "Hydraulic Cylinder Force", category: "fluid",
    expression: "F = P × A",
    description: "Thrust of a hydraulic cylinder.",
    variables: [v("P","Pressure","bar"), v("A","Piston area","cm²")],
    example: { description: "P=160 bar, A=50 cm²", inputs:{P:160,A:50}, result:"F = 80 kN" },
    keywords: ["hydraulic","cylinder","force","pressure"] },
  { id: "pipe_velocity", name: "Pipe Flow Velocity", category: "fluid",
    expression: "v = (4 × Q) ÷ (π × D²)",
    description: "Mean velocity in a circular pipe.",
    variables: [v("Q","Flow","m³/s"), v("D","Inside diameter","m")],
    example: { description: "Q=0.005, D=0.05", inputs:{Q:0.005,D:0.05}, result:"v ≈ 2.55 m/s" },
    keywords: ["pipe","velocity","flow","diameter"], calcLink: "/dashboard/converter" },

  // ═══ CHEMISTRY ════════════════════════════════════════════════════════════
  { id: "moles", name: "Moles from Mass", category: "chemistry",
    expression: "n = m ÷ M",
    description: "Amount of substance from mass and molar mass.",
    variables: [v("m","Mass","g"), v("M","Molar mass","g/mol")],
    example: { description: "18 g water", inputs:{m:18,M:18}, result:"n = 1 mol" },
    keywords: ["mole","molar","mass","chemistry"] },
  { id: "ideal_gas", name: "Ideal Gas Law", category: "chemistry",
    expression: "P × V = n × R × T",
    description: "State equation of an ideal gas.",
    variables: [v("P","Pressure","Pa"), v("V","Volume","m³"), v("n","Moles"), v("T","Temperature","K")],
    example: { description: "1 mol at 273 K, 1 atm", inputs:{n:1,T:273}, result:"V ≈ 0.0224 m³" },
    keywords: ["ideal gas","pv=nrt","pressure","volume"] },
  { id: "molarity", name: "Molarity", category: "chemistry",
    expression: "C = n ÷ V",
    description: "Concentration of a solution.",
    variables: [v("n","Moles","mol"), v("V","Volume","L")],
    example: { description: "0.5 mol in 2 L", inputs:{n:0.5,V:2}, result:"C = 0.25 M" },
    keywords: ["molarity","concentration","solution"] },
  { id: "ph", name: "pH of a Solution", category: "chemistry",
    expression: "pH = −log₁₀[H⁺]",
    description: "Acidity from hydrogen ion concentration.",
    variables: [v("[H⁺]","Ion concentration","mol/L")],
    example: { description: "[H⁺]=1e−3", inputs:{H:0.001}, result:"pH = 3" },
    keywords: ["ph","acid","base","coolant"] },
  { id: "plating_faraday", name: "Faraday's Law of Electrolysis", category: "chemistry",
    expression: "m = (Q × M) ÷ (z × F)",
    description: "Mass deposited during electroplating.",
    variables: [v("Q","Charge","C"), v("M","Molar mass","g/mol"), v("z","Valency"), v("F","Faraday constant","C/mol")],
    example: { description: "Copper, 9650 C", inputs:{Q:9650,M:63.5,z:2}, result:"m ≈ 3.18 g" },
    keywords: ["electroplating","faraday","electrolysis","coating"] },

  // ═══ FINANCE / COSTING ════════════════════════════════════════════════════
  { id: "machine_hour_rate", name: "Machine Hour Rate", category: "finance",
    expression: "MHR = (Fixed + Variable) ÷ Operating hours",
    description: "Cost of running a machine per hour.",
    variables: [v("Fixed","Fixed cost","currency"), v("Variable","Variable cost","currency"), v("h","Hours")],
    example: { description: "€40k/yr over 2000 h", inputs:{Fixed:40000,h:2000}, result:"MHR = €20/h" },
    keywords: ["cost","machine hour","rate","quoting"] },
  { id: "part_cost", name: "Cost per Part", category: "finance",
    expression: "C = (T × MHR ÷ 60) + Material + Tooling",
    description: "Total manufactured cost of one part.",
    variables: [v("T","Cycle time","min"), v("MHR","Machine hour rate","currency/h")],
    example: { description: "T=6 min, MHR=60, mat=5", inputs:{T:6,MHR:60}, result:"C = €11 + tooling" },
    related: ["machine_hour_rate"], keywords: ["cost","part","quote","pricing"] },
  { id: "breakeven", name: "Break-Even Quantity", category: "finance",
    expression: "Q = Fixed ÷ (Price − Variable)",
    description: "Units needed to cover fixed costs.",
    variables: [v("Fixed","Fixed cost"), v("Price","Selling price"), v("Variable","Variable cost per unit")],
    example: { description: "Fixed 5000, price 25, var 15", inputs:{F:5000,P:25,V:15}, result:"Q = 500 units" },
    keywords: ["break even","cost","quantity","profit"] },
  { id: "markup_margin", name: "Markup vs Margin", category: "finance",
    expression: "Margin % = (Price − Cost) ÷ Price × 100",
    description: "Gross margin from cost and selling price.",
    variables: [v("Cost","Cost"), v("Price","Selling price")],
    example: { description: "Cost 80, price 100", inputs:{C:80,P:100}, result:"Margin = 20%" },
    keywords: ["margin","markup","profit","price"] },
  { id: "oee", name: "Overall Equipment Effectiveness", category: "finance",
    expression: "OEE = Availability × Performance × Quality",
    description: "Composite measure of manufacturing productivity.",
    variables: [v("A","Availability"), v("P","Performance"), v("Q","Quality")],
    example: { description: "0.9 × 0.95 × 0.99", inputs:{A:0.9,P:0.95,Q:0.99}, result:"OEE = 84.6%" },
    keywords: ["oee","productivity","utilisation","lean"] },
  { id: "roi", name: "Return on Investment", category: "finance",
    expression: "ROI = (Gain − Cost) ÷ Cost × 100",
    description: "Percentage return on a capital purchase.",
    variables: [v("Gain","Return"), v("Cost","Investment")],
    example: { description: "Gain 130k, cost 100k", inputs:{G:130000,C:100000}, result:"ROI = 30%" },
    keywords: ["roi","payback","investment","capex"] },
  { id: "payback", name: "Payback Period", category: "finance",
    expression: "Payback = Investment ÷ Annual savings",
    description: "Years to recover a capital investment.",
    variables: [v("I","Investment"), v("S","Annual saving")],
    example: { description: "100k ÷ 40k", inputs:{I:100000,S:40000}, result:"2.5 years" },
    keywords: ["payback","investment","savings"] },
  { id: "compound_interest", name: "Compound Interest", category: "finance",
    expression: "A = P × (1 + r ÷ n)^(n × t)",
    description: "Future value with compounding.",
    variables: [v("P","Principal"), v("r","Annual rate"), v("n","Compounds/yr"), v("t","Years")],
    example: { description: "1000 at 5% for 10 y", inputs:{P:1000,r:0.05,n:1,t:10}, result:"A = 1628.89" },
    keywords: ["interest","compound","finance","future value"] },

  // ═══ UNIT CONVERSION ══════════════════════════════════════════════════════
  { id: "mm_inch", name: "Millimetres ↔ Inches", category: "unit",
    expression: "in = mm ÷ 25.4",
    description: "Length conversion between metric and imperial.",
    variables: [v("mm","Millimetres","mm"), v("in","Inches","in")],
    example: { description: "25.4 mm", inputs:{mm:25.4}, result:"1 in" },
    keywords: ["mm","inch","convert","length"], calcLink: "/dashboard/converter" },
  { id: "sfm_vc", name: "SFM ↔ m/min", category: "unit",
    expression: "m/min = SFM × 0.3048",
    description: "Cutting speed conversion.",
    variables: [v("SFM","Surface feet per minute"), v("Vc","Metres per minute","m/min")],
    example: { description: "500 SFM", inputs:{SFM:500}, result:"152.4 m/min" },
    keywords: ["sfm","cutting speed","convert"], calcLink: "/dashboard/converter" },
  { id: "ipr_mmrev", name: "IPR ↔ mm/rev", category: "unit",
    expression: "mm/rev = IPR × 25.4",
    description: "Feed rate conversion.",
    variables: [v("IPR","Inches per revolution"), v("f","mm per revolution","mm/rev")],
    example: { description: "0.010 IPR", inputs:{IPR:0.01}, result:"0.254 mm/rev" },
    keywords: ["ipr","feed","convert"], calcLink: "/dashboard/converter" },
  { id: "psi_bar", name: "PSI ↔ Bar", category: "unit",
    expression: "bar = psi ÷ 14.5038",
    description: "Pressure conversion.",
    variables: [v("psi","Pounds per square inch"), v("bar","Bar")],
    example: { description: "1000 psi", inputs:{psi:1000}, result:"68.95 bar" },
    keywords: ["psi","bar","pressure","convert"], calcLink: "/dashboard/converter" },
  { id: "hp_kw", name: "Horsepower ↔ kW", category: "unit",
    expression: "kW = hp × 0.7457",
    description: "Power conversion.",
    variables: [v("hp","Horsepower"), v("kW","Kilowatts")],
    example: { description: "10 hp", inputs:{hp:10}, result:"7.457 kW" },
    keywords: ["hp","kw","power","convert"], calcLink: "/dashboard/converter" },
  { id: "nm_lbft", name: "N·m ↔ lb·ft", category: "unit",
    expression: "lb·ft = N·m × 0.73756",
    description: "Torque conversion.",
    variables: [v("Nm","Newton metres"), v("lbft","Pound feet")],
    example: { description: "100 N·m", inputs:{Nm:100}, result:"73.76 lb·ft" },
    keywords: ["torque","nm","lbft","convert"], calcLink: "/dashboard/converter" },
  { id: "kg_lb", name: "Kilograms ↔ Pounds", category: "unit",
    expression: "lb = kg × 2.20462",
    description: "Mass conversion.",
    variables: [v("kg","Kilograms"), v("lb","Pounds")],
    example: { description: "10 kg", inputs:{kg:10}, result:"22.05 lb" },
    keywords: ["kg","lb","weight","convert"], calcLink: "/dashboard/weight" },
  { id: "mpa_ksi", name: "MPa ↔ ksi", category: "unit",
    expression: "ksi = MPa ÷ 6.89476",
    description: "Stress and strength conversion.",
    variables: [v("MPa","Megapascals"), v("ksi","Kilopounds per square inch")],
    example: { description: "500 MPa", inputs:{MPa:500}, result:"72.5 ksi" },
    keywords: ["mpa","ksi","stress","convert"], calcLink: "/dashboard/converter" },

  // ═══ MATERIAL & PIPE ══════════════════════════════════════════════════════
  { id: "round_bar_weight", name: "Round Bar Weight", category: "material",
    expression: "W = (π × d² ÷ 4) × L × ρ ÷ 1e6",
    description: "Mass of a solid round bar.",
    variables: [v("d","Diameter","mm"), v("L","Length","mm"), v("ρ","Density","g/cm³")],
    example: { description: "Ø50 × 1000 steel", inputs:{d:50,L:1000,rho:7.85}, result:"W ≈ 15.4 kg" },
    keywords: ["round bar","weight","mass","steel"], calcLink: "/dashboard/weight" },
  { id: "plate_weight", name: "Plate Weight", category: "material",
    expression: "W = L × W × T × ρ ÷ 1e6",
    description: "Mass of a rectangular plate.",
    variables: [v("L","Length","mm"), v("W","Width","mm"), v("T","Thickness","mm"), v("ρ","Density","g/cm³")],
    example: { description: "1000×500×10 steel", inputs:{L:1000,W:500,T:10}, result:"W ≈ 39.3 kg" },
    keywords: ["plate","sheet","weight","mass"], calcLink: "/dashboard/weight" },
  { id: "tube_weight", name: "Tube / Pipe Weight", category: "pipe",
    expression: "W = π × (D − t) × t × L × ρ ÷ 1e6",
    description: "Mass of a hollow round tube.",
    variables: [v("D","Outside diameter","mm"), v("t","Wall thickness","mm"), v("L","Length","mm"), v("ρ","Density","g/cm³")],
    example: { description: "Ø50 × 5 wall × 1000", inputs:{D:50,t:5,L:1000}, result:"W ≈ 5.55 kg" },
    keywords: ["tube","pipe","weight","hollow"], calcLink: "/dashboard/weight" },
  { id: "pipe_area", name: "Pipe Internal Cross-Section", category: "pipe",
    expression: "A = π × (D − 2t)² ÷ 4",
    description: "Bore area of a pipe.",
    variables: [v("D","Outside diameter","mm"), v("t","Wall thickness","mm")],
    example: { description: "Ø50 × 5 wall", inputs:{D:50,t:5}, result:"A = 1256.6 mm²" },
    keywords: ["pipe","bore","area","cross section"] },
  { id: "barlow", name: "Barlow's Formula (pipe pressure)", category: "pipe",
    expression: "P = (2 × S × t) ÷ D",
    description: "Internal pressure capacity of a pipe.",
    variables: [v("S","Allowable stress","MPa"), v("t","Wall thickness","mm"), v("D","Outside diameter","mm")],
    example: { description: "S=138, t=5, D=50", inputs:{S:138,t:5,D:50}, result:"P = 27.6 MPa" },
    keywords: ["barlow","pipe","pressure","burst","wall"] },
  { id: "hardness_conv", name: "Hardness to Tensile (steel)", category: "material",
    expression: "Rm ≈ 3.45 × HB",
    description: "Approximate tensile strength from Brinell hardness for steel.",
    variables: [v("HB","Brinell hardness"), v("Rm","Tensile strength","MPa")],
    example: { description: "HB = 200", inputs:{HB:200}, result:"Rm ≈ 690 MPa" },
    notes: "Approximation for carbon and low-alloy steels only.",
    keywords: ["hardness","brinell","tensile","conversion"], calcLink: "/dashboard/materials" },
];
