import type { FormulaEntry } from "./types";
import { EXTENDED_FORMULAS } from "./database-extended";

const v = (symbol: string, name: string, unit?: string) => ({ symbol, name, unit });

const CORE_FORMULAS: FormulaEntry[] = [
  // ═══ ALGEBRA ══════════════════════════════════════════════════════════════
  {
    id: "quadratic",
    name: "Quadratic Formula",
    category: "algebra",
    expression: "x = (−b ± √(b²−4ac)) / 2a",
    description: "Solves ax² + bx + c = 0 for x.",
    variables: [v("a", "Coefficient a"), v("b", "Coefficient b"), v("c", "Coefficient c")],
    example: {
      description: "2x²+5x+3=0",
      inputs: { a: 2, b: 5, c: 3 },
      result: "x = −1 or x = −1.5",
    },
    keywords: ["quadratic", "equation", "roots", "polynomial", "solve"],
    calcLink: "/dashboard/scientific",
  },
  {
    id: "pythag",
    name: "Pythagorean Theorem",
    category: "algebra",
    expression: "c = √(a² + b²)",
    description: "Hypotenuse of a right triangle from two sides.",
    variables: [v("a", "Side a", "m"), v("b", "Side b", "m"), v("c", "Hypotenuse", "m")],
    example: { description: "a=3, b=4", inputs: { a: 3, b: 4 }, result: "c = 5" },
    related: ["trig_sin"],
    keywords: ["pythagoras", "hypotenuse", "right triangle"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "percentage",
    name: "Percentage",
    category: "algebra",
    expression: "P = (Part / Whole) × 100",
    description: "Calculate percentage of a value.",
    variables: [v("Part", "Part value"), v("Whole", "Total value"), v("P", "Percentage", "%")],
    example: {
      description: "25 out of 200",
      inputs: { Part: 25, Whole: 200 },
      result: "P = 12.5%",
    },
    keywords: ["percent", "ratio", "proportion"],
  },

  // ═══ GEOMETRY ═════════════════════════════════════════════════════════════
  {
    id: "circle_area",
    name: "Circle Area",
    category: "geometry",
    expression: "A = π r²",
    description: "Area of a circle from its radius.",
    variables: [v("r", "Radius", "m"), v("A", "Area", "m²")],
    example: { description: "r = 5", inputs: { r: 5 }, result: "A = 78.54" },
    related: ["circle_circ"],
    keywords: ["circle", "area", "radius", "pi"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "circle_circ",
    name: "Circle Circumference",
    category: "geometry",
    expression: "C = 2πr",
    description: "Circumference of a circle.",
    variables: [v("r", "Radius", "m"), v("C", "Circumference", "m")],
    example: { description: "r = 5", inputs: { r: 5 }, result: "C = 31.42" },
    related: ["circle_area"],
    keywords: ["circle", "circumference", "perimeter"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "sphere_vol",
    name: "Sphere Volume",
    category: "geometry",
    expression: "V = (4/3)πr³",
    description: "Volume of a sphere.",
    variables: [v("r", "Radius", "m"), v("V", "Volume", "m³")],
    example: { description: "r = 3", inputs: { r: 3 }, result: "V = 113.1" },
    keywords: ["sphere", "volume", "ball"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "cyl_vol",
    name: "Cylinder Volume",
    category: "geometry",
    expression: "V = πr²h",
    description: "Volume of a cylinder.",
    variables: [v("r", "Radius", "m"), v("h", "Height", "m"), v("V", "Volume", "m³")],
    example: { description: "r=2, h=10", inputs: { r: 2, h: 10 }, result: "V = 125.66" },
    keywords: ["cylinder", "volume", "tube"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "cone_vol",
    name: "Cone Volume",
    category: "geometry",
    expression: "V = (1/3)πr²h",
    description: "Volume of a cone.",
    variables: [v("r", "Base Radius", "m"), v("h", "Height", "m")],
    example: { description: "r=3, h=7", inputs: { r: 3, h: 7 }, result: "V = 65.97" },
    keywords: ["cone", "volume"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "rect_area",
    name: "Rectangle Area",
    category: "geometry",
    expression: "A = l × w",
    description: "Area of a rectangle.",
    variables: [v("l", "Length", "m"), v("w", "Width", "m")],
    example: { description: "l=8, w=5", inputs: { l: 8, w: 5 }, result: "A = 40" },
    keywords: ["rectangle", "area", "length", "width"],
    calcLink: "/dashboard/geometry",
  },
  {
    id: "heron",
    name: "Heron's Formula",
    category: "geometry",
    expression: "A = √[s(s−a)(s−b)(s−c)]  where s=(a+b+c)/2",
    description: "Triangle area from three sides.",
    variables: [v("a", "Side a", "m"), v("b", "Side b", "m"), v("c", "Side c", "m")],
    example: { description: "a=3,b=4,c=5", inputs: { a: 3, b: 4, c: 5 }, result: "A = 6" },
    keywords: ["heron", "triangle", "area", "three sides"],
    calcLink: "/dashboard/geometry",
  },

  // ═══ TRIGONOMETRY ═════════════════════════════════════════════════════════
  {
    id: "law_sines",
    name: "Law of Sines",
    category: "trigonometry",
    expression: "a/sin(A) = b/sin(B) = c/sin(C)",
    description: "Relates sides and angles of any triangle.",
    variables: [v("a,b,c", "Sides", "m"), v("A,B,C", "Opposite angles", "°")],
    example: {
      description: "a=7, A=30°, B=45°",
      inputs: { a: 7, A: 30, B: 45 },
      result: "b = 9.90",
    },
    related: ["law_cosines"],
    keywords: ["sine", "triangle", "angle", "side"],
    calcLink: "/dashboard/scientific",
  },
  {
    id: "law_cosines",
    name: "Law of Cosines",
    category: "trigonometry",
    expression: "c² = a² + b² − 2ab·cos(C)",
    description: "Find a side or angle given two sides and included angle.",
    variables: [v("a", "Side a", "m"), v("b", "Side b", "m"), v("C", "Included angle", "°")],
    example: { description: "a=5,b=7,C=60°", inputs: { a: 5, b: 7, C: 60 }, result: "c = 6.24" },
    related: ["law_sines"],
    keywords: ["cosine", "triangle", "SSS", "SAS"],
    calcLink: "/dashboard/scientific",
  },
  {
    id: "trig_sin",
    name: "SOH-CAH-TOA",
    category: "trigonometry",
    expression: "sin=O/H  cos=A/H  tan=O/A",
    description: "Right triangle trigonometric ratios.",
    variables: [v("O", "Opposite"), v("A", "Adjacent"), v("H", "Hypotenuse")],
    example: { description: "O=3,H=5", inputs: { O: 3, H: 5 }, result: "sin(θ) = 0.6, θ = 36.87°" },
    keywords: ["sine", "cosine", "tangent", "sohcahtoa", "right triangle"],
    calcLink: "/dashboard/scientific",
  },

  // ═══ STATISTICS ═══════════════════════════════════════════════════════════
  {
    id: "mean",
    name: "Arithmetic Mean",
    category: "statistics",
    expression: "x̄ = Σxᵢ / n",
    description: "Average of a set of numbers.",
    variables: [v("xᵢ", "Data values"), v("n", "Count")],
    example: { description: "2,4,6,8", inputs: { sum: 20, n: 4 }, result: "x̄ = 5" },
    keywords: ["mean", "average", "sum"],
  },
  {
    id: "std_dev",
    name: "Standard Deviation",
    category: "statistics",
    expression: "σ = √[Σ(xᵢ−x̄)² / n]",
    description: "Measure of spread in a dataset.",
    variables: [v("xᵢ", "Data values"), v("x̄", "Mean"), v("n", "Count")],
    example: { description: "1,2,3,4,5", inputs: { mean: 3, n: 5 }, result: "σ = 1.414" },
    keywords: ["standard deviation", "variance", "spread", "dispersion"],
  },

  // ═══ MACHINING ════════════════════════════════════════════════════════════
  {
    id: "rpm",
    name: "RPM (Spindle Speed)",
    category: "machining",
    expression: "N = (Vc × 1000) / (π × D)",
    description: "Calculate spindle speed from cutting speed and diameter.",
    variables: [
      v("Vc", "Cutting speed", "m/min"),
      v("D", "Diameter", "mm"),
      v("N", "RPM", "rev/min"),
    ],
    example: {
      description: "Vc=100 m/min, D=20mm",
      inputs: { Vc: 100, D: 20 },
      result: "N = 1592 RPM",
    },
    related: ["surface_speed", "feed_rate"],
    keywords: ["rpm", "spindle", "speed", "cutting"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "surface_speed",
    name: "Surface Speed",
    category: "machining",
    expression: "Vc = (π × D × N) / 1000",
    description: "Cutting speed from RPM and diameter.",
    variables: [v("D", "Diameter", "mm"), v("N", "RPM"), v("Vc", "Surface speed", "m/min")],
    example: {
      description: "D=20, N=1500",
      inputs: { D: 20, N: 1500 },
      result: "Vc = 94.25 m/min",
    },
    related: ["rpm"],
    keywords: ["surface", "cutting speed", "sfm"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "feed_rate",
    name: "Feed Rate",
    category: "milling",
    expression: "Vf = N × z × fz",
    description: "Table feed rate from RPM, teeth, and chip load.",
    variables: [
      v("N", "RPM"),
      v("z", "Number of teeth"),
      v("fz", "Chip load", "mm/tooth"),
      v("Vf", "Feed rate", "mm/min"),
    ],
    example: {
      description: "N=3000, z=4, fz=0.05",
      inputs: { N: 3000, z: 4, fz: 0.05 },
      result: "Vf = 600 mm/min",
    },
    related: ["rpm", "chip_load"],
    keywords: ["feed", "rate", "table feed", "ipm"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "chip_load",
    name: "Chip Load",
    category: "milling",
    expression: "fz = Vf / (N × z)",
    description: "Chip load per tooth from feed rate, RPM, and teeth.",
    variables: [v("Vf", "Feed rate", "mm/min"), v("N", "RPM"), v("z", "Teeth")],
    example: {
      description: "Vf=600, N=3000, z=4",
      inputs: { Vf: 600, N: 3000, z: 4 },
      result: "fz = 0.05 mm",
    },
    related: ["feed_rate"],
    keywords: ["chip", "load", "tooth", "ipt"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "machining_time",
    name: "Machining Time",
    category: "machining",
    expression: "T = (L × passes) / Vf",
    description: "Estimate cycle time from cut length and feed rate.",
    variables: [
      v("L", "Cut length", "mm"),
      v("Vf", "Feed rate", "mm/min"),
      v("passes", "Number of passes"),
    ],
    example: {
      description: "L=200, Vf=400, 1 pass",
      inputs: { L: 200, Vf: 400, passes: 1 },
      result: "T = 0.5 min",
    },
    keywords: ["time", "cycle", "machining", "estimate"],
    calcLink: "/dashboard/machining",
  },

  // ═══ TURNING ══════════════════════════════════════════════════════════════
  {
    id: "turn_feed",
    name: "Turning Feed Rate",
    category: "turning",
    expression: "Vf = N × f",
    description: "Linear feed rate from RPM and feed per revolution.",
    variables: [v("N", "RPM"), v("f", "Feed/rev", "mm/rev"), v("Vf", "Feed rate", "mm/min")],
    example: {
      description: "N=1000, f=0.25",
      inputs: { N: 1000, f: 0.25 },
      result: "Vf = 250 mm/min",
    },
    keywords: ["turning", "feed", "lathe"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "mrr_turn",
    name: "Turning MRR",
    category: "turning",
    expression: "MRR = Vc × f × ap",
    description: "Material removal rate in turning (cm³/min).",
    variables: [
      v("Vc", "Cutting speed", "m/min"),
      v("f", "Feed", "mm/rev"),
      v("ap", "Depth of cut", "mm"),
    ],
    example: {
      description: "Vc=100,f=0.2,ap=2",
      inputs: { Vc: 100, f: 0.2, ap: 2 },
      result: "MRR = 40 cm³/min",
    },
    keywords: ["mrr", "removal", "turning", "lathe"],
    calcLink: "/dashboard/machining",
  },

  // ═══ DRILLING ═════════════════════════════════════════════════════════════
  {
    id: "drill_rpm",
    name: "Drill RPM",
    category: "drilling",
    expression: "N = (Vc × 1000) / (π × D)",
    description: "Spindle speed for drilling.",
    variables: [v("Vc", "Cutting speed", "m/min"), v("D", "Drill diameter", "mm")],
    example: { description: "Vc=25, D=10", inputs: { Vc: 25, D: 10 }, result: "N = 796 RPM" },
    keywords: ["drill", "rpm", "speed", "hole"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "drill_feed",
    name: "Drill Feed Rate",
    category: "drilling",
    expression: "Vf = N × f",
    description: "Linear feed for drilling.",
    variables: [v("N", "RPM"), v("f", "Feed/rev", "mm/rev")],
    example: {
      description: "N=800, f=0.15",
      inputs: { N: 800, f: 0.15 },
      result: "Vf = 120 mm/min",
    },
    keywords: ["drill", "feed", "plunge"],
    calcLink: "/dashboard/machining",
  },

  // ═══ THREADING ════════════════════════════════════════════════════════════
  {
    id: "tap_drill",
    name: "Tap Drill Size",
    category: "threading",
    expression: "D_tap = D_major − Pitch",
    description: "Recommended drill size for 75% thread depth.",
    variables: [v("D_major", "Major diameter", "mm"), v("Pitch", "Thread pitch", "mm")],
    example: {
      description: "M10×1.5",
      inputs: { D_major: 10, Pitch: 1.5 },
      result: "D_tap = 8.5 mm",
    },
    notes: "For ~75% thread engagement.",
    keywords: ["tap", "drill", "thread", "tapping"],
    calcLink: "/dashboard/machining",
  },
  {
    id: "thread_minor",
    name: "Thread Minor Diameter",
    category: "threading",
    expression: "d_minor = D − 1.0825 × P",
    description: "ISO metric minor diameter calculation.",
    variables: [v("D", "Major diameter", "mm"), v("P", "Pitch", "mm")],
    example: { description: "M10×1.5", inputs: { D: 10, P: 1.5 }, result: "d_minor = 8.376 mm" },
    keywords: ["thread", "minor", "diameter", "ISO"],
    calcLink: "/dashboard/machining",
  },

  // ═══ MATERIAL WEIGHT ══════════════════════════════════════════════════════
  {
    id: "weight_basic",
    name: "Material Weight",
    category: "material",
    expression: "W = V × ρ",
    description: "Weight from volume and density.",
    variables: [v("V", "Volume", "m³"), v("ρ", "Density", "kg/m³"), v("W", "Weight", "kg")],
    example: {
      description: "0.001 m³ of steel",
      inputs: { V: 0.001, ρ: 7850 },
      result: "W = 7.85 kg",
    },
    keywords: ["weight", "mass", "density", "volume"],
    calcLink: "/dashboard/weight",
  },
  {
    id: "pipe_weight",
    name: "Pipe Weight",
    category: "pipe",
    expression: "W = (π/4)(OD²−ID²) × L × ρ",
    description: "Weight of a hollow pipe or tube.",
    variables: [
      v("OD", "Outside diameter", "m"),
      v("ID", "Inside diameter", "m"),
      v("L", "Length", "m"),
      v("ρ", "Density", "kg/m³"),
    ],
    example: {
      description: "OD=50, ID=40, L=1m, Steel",
      inputs: { OD: 0.05, ID: 0.04, L: 1, ρ: 7850 },
      result: "W = 5.55 kg",
    },
    keywords: ["pipe", "tube", "hollow", "weight"],
    calcLink: "/dashboard/weight",
  },

  // ═══ SHEET METAL ══════════════════════════════════════════════════════════
  {
    id: "bend_allow",
    name: "Bend Allowance",
    category: "sheet_metal",
    expression: "BA = A × (π/180) × (R + K × T)",
    description: "Material needed for a bend.",
    variables: [
      v("A", "Bend angle", "°"),
      v("R", "Inside radius", "mm"),
      v("T", "Thickness", "mm"),
      v("K", "K-factor", "—"),
    ],
    example: {
      description: "90°, R=2, T=1, K=0.33",
      inputs: { A: 90, R: 2, T: 1, K: 0.33 },
      result: "BA = 3.66 mm",
    },
    notes: "K-factor typically 0.33–0.50.",
    keywords: ["bend", "allowance", "sheet", "metal", "brake"],
  },
  {
    id: "flat_length",
    name: "Flat Pattern Length",
    category: "sheet_metal",
    expression: "L_flat = L₁ + L₂ + BA",
    description: "Total flat length including bend allowance.",
    variables: [v("L₁", "Leg 1", "mm"), v("L₂", "Leg 2", "mm"), v("BA", "Bend allowance", "mm")],
    example: {
      description: "L₁=50, L₂=30, BA=3.66",
      inputs: { L1: 50, L2: 30, BA: 3.66 },
      result: "L_flat = 83.66 mm",
    },
    keywords: ["flat", "pattern", "unfold", "sheet metal"],
  },

  // ═══ ELECTRICAL ═══════════════════════════════════════════════════════════
  {
    id: "ohms_law",
    name: "Ohm's Law",
    category: "electrical",
    expression: "V = I × R",
    description: "Voltage = Current × Resistance.",
    variables: [v("V", "Voltage", "V"), v("I", "Current", "A"), v("R", "Resistance", "Ω")],
    example: { description: "I=2A, R=10Ω", inputs: { I: 2, R: 10 }, result: "V = 20 V" },
    related: ["power_elec"],
    keywords: ["ohm", "voltage", "current", "resistance"],
    calcLink: "/dashboard/electrical",
  },
  {
    id: "power_elec",
    name: "Electrical Power",
    category: "electrical",
    expression: "P = V × I  or  P = I²R  or  P = V²/R",
    description: "Power in a DC circuit.",
    variables: [
      v("P", "Power", "W"),
      v("V", "Voltage", "V"),
      v("I", "Current", "A"),
      v("R", "Resistance", "Ω"),
    ],
    example: { description: "V=12, I=3", inputs: { V: 12, I: 3 }, result: "P = 36 W" },
    related: ["ohms_law"],
    keywords: ["power", "watt", "electrical", "dc"],
    calcLink: "/dashboard/electrical",
  },
  {
    id: "resistors_series",
    name: "Resistors in Series",
    category: "electrical",
    expression: "R_total = R₁ + R₂ + R₃ + …",
    description: "Total resistance of series resistors.",
    variables: [v("R₁,R₂…", "Resistances", "Ω")],
    example: {
      description: "10Ω + 20Ω + 30Ω",
      inputs: { R1: 10, R2: 20, R3: 30 },
      result: "R_total = 60 Ω",
    },
    keywords: ["resistor", "series", "total", "resistance"],
    calcLink: "/dashboard/electrical",
  },
  {
    id: "resistors_parallel",
    name: "Resistors in Parallel",
    category: "electrical",
    expression: "1/R_total = 1/R₁ + 1/R₂ + …",
    description: "Total resistance of parallel resistors.",
    variables: [v("R₁,R₂…", "Resistances", "Ω")],
    example: { description: "10Ω ∥ 20Ω", inputs: { R1: 10, R2: 20 }, result: "R_total = 6.67 Ω" },
    keywords: ["resistor", "parallel", "total", "resistance"],
    calcLink: "/dashboard/electrical",
  },

  // ═══ PHYSICS ══════════════════════════════════════════════════════════════
  {
    id: "force",
    name: "Newton's Second Law",
    category: "physics",
    expression: "F = m × a",
    description: "Force = mass × acceleration.",
    variables: [v("F", "Force", "N"), v("m", "Mass", "kg"), v("a", "Acceleration", "m/s²")],
    example: { description: "m=10kg, a=9.81", inputs: { m: 10, a: 9.81 }, result: "F = 98.1 N" },
    keywords: ["force", "newton", "mass", "acceleration"],
    calcLink: "/dashboard/scientific",
  },
  {
    id: "kinetic_energy",
    name: "Kinetic Energy",
    category: "physics",
    expression: "KE = ½mv²",
    description: "Energy of a moving object.",
    variables: [v("m", "Mass", "kg"), v("v", "Velocity", "m/s"), v("KE", "Kinetic energy", "J")],
    example: { description: "m=5, v=10", inputs: { m: 5, v: 10 }, result: "KE = 250 J" },
    keywords: ["kinetic", "energy", "velocity", "motion"],
  },
  {
    id: "potential_energy",
    name: "Potential Energy",
    category: "physics",
    expression: "PE = mgh",
    description: "Gravitational potential energy.",
    variables: [v("m", "Mass", "kg"), v("g", "Gravity", "m/s²"), v("h", "Height", "m")],
    // g is stated in the inputs because the reader cannot reproduce the answer
    // without it. 10 × 9.81 × 5 is 490.5 J; the 490.3 that stood here came from
    // quietly using 9.80665 while the entry above it uses 9.81.
    example: {
      description: "m=10, g=9.81, h=5",
      inputs: { m: 10, g: 9.81, h: 5 },
      result: "PE = 490.5 J",
    },
    keywords: ["potential", "energy", "gravity", "height"],
  },

  // ═══ MECHANICS ════════════════════════════════════════════════════════════
  {
    id: "stress",
    name: "Stress",
    category: "mechanics",
    expression: "σ = F / A",
    description: "Normal stress = Force / Cross-sectional area.",
    variables: [v("σ", "Stress", "Pa"), v("F", "Force", "N"), v("A", "Area", "m²")],
    example: {
      description: "F=1000N, A=0.001m²",
      inputs: { F: 1000, A: 0.001 },
      result: "σ = 1 MPa",
    },
    keywords: ["stress", "force", "area", "tension", "compression"],
  },
  {
    id: "strain",
    name: "Strain",
    category: "mechanics",
    expression: "ε = ΔL / L₀",
    description: "Engineering strain = change in length / original length.",
    variables: [
      v("ε", "Strain", "—"),
      v("ΔL", "Change in length", "m"),
      v("L₀", "Original length", "m"),
    ],
    example: {
      description: "ΔL=0.5mm, L₀=100mm",
      inputs: { dL: 0.5, L0: 100 },
      result: "ε = 0.005",
    },
    keywords: ["strain", "deformation", "elongation"],
  },
  {
    id: "hookes",
    name: "Hooke's Law",
    category: "mechanics",
    expression: "σ = E × ε",
    description: "Stress-strain relation in elastic region.",
    variables: [v("σ", "Stress", "Pa"), v("E", "Young's modulus", "Pa"), v("ε", "Strain", "—")],
    example: {
      description: "E=200GPa, ε=0.001",
      inputs: { E: 200e9, ε: 0.001 },
      result: "σ = 200 MPa",
    },
    related: ["stress", "strain"],
    keywords: ["hooke", "elastic", "modulus", "young"],
  },
  {
    id: "torque",
    // Two torque entries used to share the name "Torque" and looked like
    // duplicates in search. They are not the same formula: this one assumes the
    // force is square to the arm, `torque_phys` carries the sin θ for when it
    // is not. The names now say which is which, and each points at the other.
    name: "Torque (Force at Right Angles)",
    category: "mechanics",
    expression: "τ = F × d",
    description: "Torque from a force acting perpendicular to the lever arm — the usual shop case.",
    variables: [v("τ", "Torque", "N·m"), v("F", "Force", "N"), v("d", "Distance", "m")],
    example: { description: "F=50N, d=0.3m", inputs: { F: 50, d: 0.3 }, result: "τ = 15 N·m" },
    related: ["torque_phys"],
    keywords: ["torque", "moment", "force", "lever", "spanner", "tightening"],
  },
  {
    id: "beam_deflection",
    name: "Simply Supported Beam Deflection",
    category: "mechanics",
    expression: "δ = (5wL⁴) / (384EI)",
    description: "Max deflection of a uniformly loaded simply supported beam.",
    variables: [
      v("w", "Load/length", "N/m"),
      v("L", "Span", "m"),
      v("E", "Modulus", "Pa"),
      v("I", "Moment of inertia", "m⁴"),
    ],
    example: {
      description: "w=1000, L=3, Steel I-beam",
      inputs: { w: 1000, L: 3, E: 200e9, I: 1e-5 },
      result: "δ = 0.527 mm",
    },
    keywords: ["beam", "deflection", "bending", "structural"],
  },

  // ═══ THERMAL ══════════════════════════════════════════════════════════════
  {
    id: "heat_transfer",
    name: "Heat Energy",
    category: "thermal",
    expression: "Q = m × c × ΔT",
    description: "Heat required to change temperature.",
    variables: [
      v("Q", "Heat energy", "J"),
      v("m", "Mass", "kg"),
      v("c", "Specific heat", "J/(kg·K)"),
      v("ΔT", "Temp change", "K"),
    ],
    example: {
      description: "1kg water, ΔT=10°C",
      inputs: { m: 1, c: 4184, dT: 10 },
      result: "Q = 41,840 J",
    },
    keywords: ["heat", "thermal", "temperature", "specific heat", "calorimetry"],
  },
  {
    id: "conduction",
    name: "Fourier's Law (Conduction)",
    category: "thermal",
    expression: "Q̇ = −kA(dT/dx)",
    description: "Steady-state heat conduction through a material.",
    variables: [
      v("Q̇", "Heat flow", "W"),
      v("k", "Conductivity", "W/(m·K)"),
      v("A", "Area", "m²"),
      v("dT/dx", "Temp gradient", "K/m"),
    ],
    example: {
      description: "k=50, A=0.01, ΔT=100, L=0.05",
      inputs: { k: 50, A: 0.01, dT: 100, L: 0.05 },
      result: "Q̇ = 1000 W",
    },
    keywords: ["conduction", "fourier", "heat", "thermal", "conductivity"],
  },

  // ═══ FLUID MECHANICS ══════════════════════════════════════════════════════
  {
    id: "bernoulli",
    name: "Bernoulli's Equation",
    category: "fluid",
    expression: "P + ½ρv² + ρgh = constant",
    description: "Energy conservation in fluid flow.",
    variables: [
      v("P", "Pressure", "Pa"),
      v("ρ", "Density", "kg/m³"),
      v("v", "Velocity", "m/s"),
      v("h", "Height", "m"),
    ],
    example: {
      description: "Ideal flow",
      inputs: { P: 101325, ρ: 1000, v: 5, h: 0 },
      result: "Total = 113,825 Pa",
    },
    keywords: ["bernoulli", "pressure", "velocity", "flow", "fluid"],
  },
  {
    id: "reynolds",
    name: "Reynolds Number",
    category: "fluid",
    expression: "Re = ρvD/μ",
    description: "Determines if flow is laminar or turbulent.",
    variables: [
      v("ρ", "Density", "kg/m³"),
      v("v", "Velocity", "m/s"),
      v("D", "Diameter", "m"),
      v("μ", "Viscosity", "Pa·s"),
    ],
    example: {
      description: "Water in 25mm pipe at 1 m/s",
      inputs: { ρ: 1000, v: 1, D: 0.025, μ: 0.001 },
      result: "Re = 25,000 (turbulent)",
    },
    notes: "Laminar < 2300, Turbulent > 4000.",
    keywords: ["reynolds", "laminar", "turbulent", "flow", "pipe"],
  },
  {
    id: "flow_rate",
    name: "Volumetric Flow Rate",
    category: "fluid",
    expression: "Q = A × v",
    description: "Flow rate = cross-section area × velocity.",
    variables: [v("Q", "Flow rate", "m³/s"), v("A", "Area", "m²"), v("v", "Velocity", "m/s")],
    example: {
      description: "A=0.001m², v=2m/s",
      inputs: { A: 0.001, v: 2 },
      result: "Q = 0.002 m³/s",
    },
    keywords: ["flow", "rate", "volume", "velocity", "area"],
    calcLink: "/dashboard/converter",
  },
];

// No id appears in both sets any more — the thirteen extended copies that were
// being silently dropped here have been deleted, so the file no longer carries
// entries that could never be reached.
//
// The guard stays as a safety net. Without it a re-introduced duplicate would
// list twice on the page while FORMULA_MAP silently kept whichever came last,
// so a lookup and the list would disagree. The core entry wins, being the
// curated set. `formulas-examples.test.ts` fails on any new collision.
export const FORMULAS: FormulaEntry[] = (() => {
  const byId = new Map<string, FormulaEntry>();
  for (const f of [...CORE_FORMULAS, ...EXTENDED_FORMULAS]) {
    if (!byId.has(f.id)) byId.set(f.id, f);
  }
  return [...byId.values()];
})();

export const FORMULA_MAP = new Map(FORMULAS.map((f) => [f.id, f]));
