/**
 * Tap drill chart — reference data.
 *
 * Tap drill = the drill size for the hole BEFORE tapping. Nearly always computed
 * (major − pitch for metric; derived from the thread's basic minor dia for imperial),
 * but this table ships the values the machinist drill index actually carries —
 * closest drill in 0.1mm / letter / number / fractional inch.
 *
 * Sources follow Machinery's Handbook 30th ed., ISO 724 / ANSI B1.1 / ASME B1.20.1.
 * Clearance drills follow ISO 273 (close / medium / free fits).
 */

export type ThreadSystem =
  | "iso-coarse" // M  series
  | "iso-fine" // MF series
  | "unc" // Unified coarse
  | "unf" // Unified fine
  | "npt" // Taper pipe (USA)
  | "bsp"; // British Standard Pipe (parallel)

export interface TapDrillEntry {
  /** Stable slug, e.g. "m6x1", "unc-1-4-20", "npt-1-8-27". */
  id: string;
  system: ThreadSystem;
  /** Display designation, e.g. "M6 × 1", "¼-20 UNC", "⅛-27 NPT". */
  designation: string;
  /** Major (nominal) diameter in millimetres. */
  majorDiaMm: number;
  /** Major (nominal) diameter in inches. */
  majorDiaIn: number;
  /** Thread pitch in millimetres (metric) or null for TPI-based imperial. */
  pitchMm: number | null;
  /** Threads per inch (imperial) or null for metric. */
  tpi: number | null;
  /** Recommended tap drill size in millimetres. */
  tapDrillMm: number;
  /** Recommended tap drill size designation in inch form (e.g. "5.0 mm", "#7", "7/32″"). */
  tapDrillIn: string;
  /** ISO 273 close-fit clearance drill (mm). */
  clearanceCloseMm: number;
  /** ISO 273 medium/normal-fit clearance drill (mm). */
  clearanceNormalMm: number;
  /** ISO 273 free-fit clearance drill (mm). */
  clearanceFreeMm: number;
  /** Basic internal-thread minor diameter (mm) for reference. */
  minorDiaMm: number | null;
}

/* ------------------------------------------------------------------ */
/*  ISO Metric Coarse (M)                                              */
/* ------------------------------------------------------------------ */
const ISO_COARSE: TapDrillEntry[] = [
  {
    id: "m1x0-25",
    system: "iso-coarse",
    designation: "M1 × 0.25",
    majorDiaMm: 1.0,
    majorDiaIn: 0.0394,
    pitchMm: 0.25,
    tpi: null,
    tapDrillMm: 0.75,
    tapDrillIn: "0.75 mm",
    clearanceCloseMm: 1.1,
    clearanceNormalMm: 1.2,
    clearanceFreeMm: 1.3,
    minorDiaMm: 0.729,
  },
  {
    id: "m1-2x0-25",
    system: "iso-coarse",
    designation: "M1.2 × 0.25",
    majorDiaMm: 1.2,
    majorDiaIn: 0.0472,
    pitchMm: 0.25,
    tpi: null,
    tapDrillMm: 0.95,
    tapDrillIn: "0.95 mm",
    clearanceCloseMm: 1.3,
    clearanceNormalMm: 1.4,
    clearanceFreeMm: 1.5,
    minorDiaMm: 0.929,
  },
  {
    id: "m1-6x0-35",
    system: "iso-coarse",
    designation: "M1.6 × 0.35",
    majorDiaMm: 1.6,
    majorDiaIn: 0.063,
    pitchMm: 0.35,
    tpi: null,
    tapDrillMm: 1.25,
    tapDrillIn: "1.25 mm",
    clearanceCloseMm: 1.7,
    clearanceNormalMm: 1.8,
    clearanceFreeMm: 2.0,
    minorDiaMm: 1.221,
  },
  {
    id: "m2x0-4",
    system: "iso-coarse",
    designation: "M2 × 0.4",
    majorDiaMm: 2.0,
    majorDiaIn: 0.0787,
    pitchMm: 0.4,
    tpi: null,
    tapDrillMm: 1.6,
    tapDrillIn: "1.6 mm",
    clearanceCloseMm: 2.2,
    clearanceNormalMm: 2.4,
    clearanceFreeMm: 2.6,
    minorDiaMm: 1.567,
  },
  {
    id: "m2-5x0-45",
    system: "iso-coarse",
    designation: "M2.5 × 0.45",
    majorDiaMm: 2.5,
    majorDiaIn: 0.0984,
    pitchMm: 0.45,
    tpi: null,
    tapDrillMm: 2.05,
    tapDrillIn: "2.05 mm",
    clearanceCloseMm: 2.7,
    clearanceNormalMm: 2.9,
    clearanceFreeMm: 3.1,
    minorDiaMm: 2.013,
  },
  {
    id: "m3x0-5",
    system: "iso-coarse",
    designation: "M3 × 0.5",
    majorDiaMm: 3.0,
    majorDiaIn: 0.1181,
    pitchMm: 0.5,
    tpi: null,
    tapDrillMm: 2.5,
    tapDrillIn: "2.5 mm",
    clearanceCloseMm: 3.2,
    clearanceNormalMm: 3.4,
    clearanceFreeMm: 3.6,
    minorDiaMm: 2.459,
  },
  {
    id: "m4x0-7",
    system: "iso-coarse",
    designation: "M4 × 0.7",
    majorDiaMm: 4.0,
    majorDiaIn: 0.1575,
    pitchMm: 0.7,
    tpi: null,
    tapDrillMm: 3.3,
    tapDrillIn: "3.3 mm",
    clearanceCloseMm: 4.3,
    clearanceNormalMm: 4.5,
    clearanceFreeMm: 4.8,
    minorDiaMm: 3.242,
  },
  {
    id: "m5x0-8",
    system: "iso-coarse",
    designation: "M5 × 0.8",
    majorDiaMm: 5.0,
    majorDiaIn: 0.1969,
    pitchMm: 0.8,
    tpi: null,
    tapDrillMm: 4.2,
    tapDrillIn: "4.2 mm",
    clearanceCloseMm: 5.3,
    clearanceNormalMm: 5.5,
    clearanceFreeMm: 5.8,
    minorDiaMm: 4.134,
  },
  {
    id: "m6x1",
    system: "iso-coarse",
    designation: "M6 × 1",
    majorDiaMm: 6.0,
    majorDiaIn: 0.2362,
    pitchMm: 1.0,
    tpi: null,
    tapDrillMm: 5.0,
    tapDrillIn: "5.0 mm",
    clearanceCloseMm: 6.4,
    clearanceNormalMm: 6.6,
    clearanceFreeMm: 7.0,
    minorDiaMm: 4.917,
  },
  {
    id: "m7x1",
    system: "iso-coarse",
    designation: "M7 × 1",
    majorDiaMm: 7.0,
    majorDiaIn: 0.2756,
    pitchMm: 1.0,
    tpi: null,
    tapDrillMm: 6.0,
    tapDrillIn: "6.0 mm",
    clearanceCloseMm: 7.4,
    clearanceNormalMm: 7.6,
    clearanceFreeMm: 8.0,
    minorDiaMm: 5.917,
  },
  {
    id: "m8x1-25",
    system: "iso-coarse",
    designation: "M8 × 1.25",
    majorDiaMm: 8.0,
    majorDiaIn: 0.315,
    pitchMm: 1.25,
    tpi: null,
    tapDrillMm: 6.8,
    tapDrillIn: "6.8 mm",
    clearanceCloseMm: 8.4,
    clearanceNormalMm: 9.0,
    clearanceFreeMm: 10.0,
    minorDiaMm: 6.647,
  },
  {
    id: "m10x1-5",
    system: "iso-coarse",
    designation: "M10 × 1.5",
    majorDiaMm: 10.0,
    majorDiaIn: 0.3937,
    pitchMm: 1.5,
    tpi: null,
    tapDrillMm: 8.5,
    tapDrillIn: "8.5 mm",
    clearanceCloseMm: 10.5,
    clearanceNormalMm: 11.0,
    clearanceFreeMm: 12.0,
    minorDiaMm: 8.376,
  },
  {
    id: "m12x1-75",
    system: "iso-coarse",
    designation: "M12 × 1.75",
    majorDiaMm: 12.0,
    majorDiaIn: 0.4724,
    pitchMm: 1.75,
    tpi: null,
    tapDrillMm: 10.25,
    tapDrillIn: "10.25 mm",
    clearanceCloseMm: 13.0,
    clearanceNormalMm: 13.5,
    clearanceFreeMm: 14.5,
    minorDiaMm: 10.106,
  },
  {
    id: "m14x2",
    system: "iso-coarse",
    designation: "M14 × 2",
    majorDiaMm: 14.0,
    majorDiaIn: 0.5512,
    pitchMm: 2.0,
    tpi: null,
    tapDrillMm: 12.0,
    tapDrillIn: "12 mm",
    clearanceCloseMm: 15.0,
    clearanceNormalMm: 15.5,
    clearanceFreeMm: 16.5,
    minorDiaMm: 11.835,
  },
  {
    id: "m16x2",
    system: "iso-coarse",
    designation: "M16 × 2",
    majorDiaMm: 16.0,
    majorDiaIn: 0.6299,
    pitchMm: 2.0,
    tpi: null,
    tapDrillMm: 14.0,
    tapDrillIn: "14 mm",
    clearanceCloseMm: 17.0,
    clearanceNormalMm: 17.5,
    clearanceFreeMm: 18.5,
    minorDiaMm: 13.835,
  },
  {
    id: "m18x2-5",
    system: "iso-coarse",
    designation: "M18 × 2.5",
    majorDiaMm: 18.0,
    majorDiaIn: 0.7087,
    pitchMm: 2.5,
    tpi: null,
    tapDrillMm: 15.5,
    tapDrillIn: "15.5 mm",
    clearanceCloseMm: 19.0,
    clearanceNormalMm: 20.0,
    clearanceFreeMm: 21.0,
    minorDiaMm: 15.294,
  },
  {
    id: "m20x2-5",
    system: "iso-coarse",
    designation: "M20 × 2.5",
    majorDiaMm: 20.0,
    majorDiaIn: 0.7874,
    pitchMm: 2.5,
    tpi: null,
    tapDrillMm: 17.5,
    tapDrillIn: "17.5 mm",
    clearanceCloseMm: 21.0,
    clearanceNormalMm: 22.0,
    clearanceFreeMm: 24.0,
    minorDiaMm: 17.294,
  },
  {
    id: "m22x2-5",
    system: "iso-coarse",
    designation: "M22 × 2.5",
    majorDiaMm: 22.0,
    majorDiaIn: 0.8661,
    pitchMm: 2.5,
    tpi: null,
    tapDrillMm: 19.5,
    tapDrillIn: "19.5 mm",
    clearanceCloseMm: 23.0,
    clearanceNormalMm: 24.0,
    clearanceFreeMm: 26.0,
    minorDiaMm: 19.294,
  },
  {
    id: "m24x3",
    system: "iso-coarse",
    designation: "M24 × 3",
    majorDiaMm: 24.0,
    majorDiaIn: 0.9449,
    pitchMm: 3.0,
    tpi: null,
    tapDrillMm: 21.0,
    tapDrillIn: "21 mm",
    clearanceCloseMm: 25.0,
    clearanceNormalMm: 26.0,
    clearanceFreeMm: 28.0,
    minorDiaMm: 20.752,
  },
  {
    id: "m27x3",
    system: "iso-coarse",
    designation: "M27 × 3",
    majorDiaMm: 27.0,
    majorDiaIn: 1.063,
    pitchMm: 3.0,
    tpi: null,
    tapDrillMm: 24.0,
    tapDrillIn: "24 mm",
    clearanceCloseMm: 28.0,
    clearanceNormalMm: 30.0,
    clearanceFreeMm: 32.0,
    minorDiaMm: 23.752,
  },
  {
    id: "m30x3-5",
    system: "iso-coarse",
    designation: "M30 × 3.5",
    majorDiaMm: 30.0,
    majorDiaIn: 1.1811,
    pitchMm: 3.5,
    tpi: null,
    tapDrillMm: 26.5,
    tapDrillIn: "26.5 mm",
    clearanceCloseMm: 31.0,
    clearanceNormalMm: 33.0,
    clearanceFreeMm: 35.0,
    minorDiaMm: 26.211,
  },
];

/* ------------------------------------------------------------------ */
/*  ISO Metric Fine (MF)                                               */
/* ------------------------------------------------------------------ */
const ISO_FINE: TapDrillEntry[] = [
  {
    id: "m4x0-5",
    system: "iso-fine",
    designation: "M4 × 0.5",
    majorDiaMm: 4,
    majorDiaIn: 0.1575,
    pitchMm: 0.5,
    tpi: null,
    tapDrillMm: 3.5,
    tapDrillIn: "3.5 mm",
    clearanceCloseMm: 4.3,
    clearanceNormalMm: 4.5,
    clearanceFreeMm: 4.8,
    minorDiaMm: 3.459,
  },
  {
    id: "m5x0-5",
    system: "iso-fine",
    designation: "M5 × 0.5",
    majorDiaMm: 5,
    majorDiaIn: 0.1969,
    pitchMm: 0.5,
    tpi: null,
    tapDrillMm: 4.5,
    tapDrillIn: "4.5 mm",
    clearanceCloseMm: 5.3,
    clearanceNormalMm: 5.5,
    clearanceFreeMm: 5.8,
    minorDiaMm: 4.459,
  },
  {
    id: "m6x0-75",
    system: "iso-fine",
    designation: "M6 × 0.75",
    majorDiaMm: 6,
    majorDiaIn: 0.2362,
    pitchMm: 0.75,
    tpi: null,
    tapDrillMm: 5.25,
    tapDrillIn: "5.25 mm",
    clearanceCloseMm: 6.4,
    clearanceNormalMm: 6.6,
    clearanceFreeMm: 7.0,
    minorDiaMm: 5.188,
  },
  {
    id: "m8x0-75",
    system: "iso-fine",
    designation: "M8 × 0.75",
    majorDiaMm: 8,
    majorDiaIn: 0.315,
    pitchMm: 0.75,
    tpi: null,
    tapDrillMm: 7.25,
    tapDrillIn: "7.25 mm",
    clearanceCloseMm: 8.4,
    clearanceNormalMm: 9.0,
    clearanceFreeMm: 10.0,
    minorDiaMm: 7.188,
  },
  {
    id: "m8x1",
    system: "iso-fine",
    designation: "M8 × 1",
    majorDiaMm: 8,
    majorDiaIn: 0.315,
    pitchMm: 1.0,
    tpi: null,
    tapDrillMm: 7.0,
    tapDrillIn: "7.0 mm",
    clearanceCloseMm: 8.4,
    clearanceNormalMm: 9.0,
    clearanceFreeMm: 10.0,
    minorDiaMm: 6.917,
  },
  {
    id: "m10x1",
    system: "iso-fine",
    designation: "M10 × 1",
    majorDiaMm: 10,
    majorDiaIn: 0.3937,
    pitchMm: 1.0,
    tpi: null,
    tapDrillMm: 9.0,
    tapDrillIn: "9 mm",
    clearanceCloseMm: 10.5,
    clearanceNormalMm: 11.0,
    clearanceFreeMm: 12.0,
    minorDiaMm: 8.917,
  },
  {
    id: "m10x1-25",
    system: "iso-fine",
    designation: "M10 × 1.25",
    majorDiaMm: 10,
    majorDiaIn: 0.3937,
    pitchMm: 1.25,
    tpi: null,
    tapDrillMm: 8.75,
    tapDrillIn: "8.75 mm",
    clearanceCloseMm: 10.5,
    clearanceNormalMm: 11.0,
    clearanceFreeMm: 12.0,
    minorDiaMm: 8.647,
  },
  {
    id: "m12x1-25",
    system: "iso-fine",
    designation: "M12 × 1.25",
    majorDiaMm: 12,
    majorDiaIn: 0.4724,
    pitchMm: 1.25,
    tpi: null,
    tapDrillMm: 10.75,
    tapDrillIn: "10.75 mm",
    clearanceCloseMm: 13.0,
    clearanceNormalMm: 13.5,
    clearanceFreeMm: 14.5,
    minorDiaMm: 10.647,
  },
  {
    id: "m12x1-5",
    system: "iso-fine",
    designation: "M12 × 1.5",
    majorDiaMm: 12,
    majorDiaIn: 0.4724,
    pitchMm: 1.5,
    tpi: null,
    tapDrillMm: 10.5,
    tapDrillIn: "10.5 mm",
    clearanceCloseMm: 13.0,
    clearanceNormalMm: 13.5,
    clearanceFreeMm: 14.5,
    minorDiaMm: 10.376,
  },
];

/* ------------------------------------------------------------------ */
/*  UNC (Unified National Coarse)                                      */
/* ------------------------------------------------------------------ */
const UNC: TapDrillEntry[] = [
  {
    id: "unc-4-40",
    system: "unc",
    designation: "#4-40 UNC",
    majorDiaMm: 2.845,
    majorDiaIn: 0.112,
    pitchMm: null,
    tpi: 40,
    tapDrillMm: 2.26,
    tapDrillIn: "#43",
    clearanceCloseMm: 3.0,
    clearanceNormalMm: 3.2,
    clearanceFreeMm: 3.4,
    minorDiaMm: 2.156,
  },
  {
    id: "unc-6-32",
    system: "unc",
    designation: "#6-32 UNC",
    majorDiaMm: 3.505,
    majorDiaIn: 0.138,
    pitchMm: null,
    tpi: 32,
    tapDrillMm: 2.85,
    tapDrillIn: "#36",
    clearanceCloseMm: 3.7,
    clearanceNormalMm: 3.9,
    clearanceFreeMm: 4.2,
    minorDiaMm: 2.642,
  },
  {
    id: "unc-8-32",
    system: "unc",
    designation: "#8-32 UNC",
    majorDiaMm: 4.166,
    majorDiaIn: 0.164,
    pitchMm: null,
    tpi: 32,
    tapDrillMm: 3.5,
    tapDrillIn: "#29",
    clearanceCloseMm: 4.3,
    clearanceNormalMm: 4.5,
    clearanceFreeMm: 4.8,
    minorDiaMm: 3.302,
  },
  {
    id: "unc-10-24",
    system: "unc",
    designation: "#10-24 UNC",
    majorDiaMm: 4.826,
    majorDiaIn: 0.19,
    pitchMm: null,
    tpi: 24,
    tapDrillMm: 3.9,
    tapDrillIn: "#25",
    clearanceCloseMm: 5.0,
    clearanceNormalMm: 5.2,
    clearanceFreeMm: 5.5,
    minorDiaMm: 3.683,
  },
  {
    id: "unc-1-4-20",
    system: "unc",
    designation: "¼-20 UNC",
    majorDiaMm: 6.35,
    majorDiaIn: 0.25,
    pitchMm: null,
    tpi: 20,
    tapDrillMm: 5.1,
    tapDrillIn: "#7",
    clearanceCloseMm: 6.6,
    clearanceNormalMm: 7.0,
    clearanceFreeMm: 7.4,
    minorDiaMm: 4.976,
  },
  {
    id: "unc-5-16-18",
    system: "unc",
    designation: "5/16-18 UNC",
    majorDiaMm: 7.938,
    majorDiaIn: 0.313,
    pitchMm: null,
    tpi: 18,
    tapDrillMm: 6.6,
    tapDrillIn: "F",
    clearanceCloseMm: 8.2,
    clearanceNormalMm: 8.6,
    clearanceFreeMm: 9.1,
    minorDiaMm: 6.411,
  },
  {
    id: "unc-3-8-16",
    system: "unc",
    designation: "⅜-16 UNC",
    majorDiaMm: 9.525,
    majorDiaIn: 0.375,
    pitchMm: null,
    tpi: 16,
    tapDrillMm: 8.0,
    tapDrillIn: "5/16″",
    clearanceCloseMm: 9.9,
    clearanceNormalMm: 10.4,
    clearanceFreeMm: 11.0,
    minorDiaMm: 7.805,
  },
  {
    id: "unc-7-16-14",
    system: "unc",
    designation: "7/16-14 UNC",
    majorDiaMm: 11.113,
    majorDiaIn: 0.438,
    pitchMm: null,
    tpi: 14,
    tapDrillMm: 9.3,
    tapDrillIn: "U",
    clearanceCloseMm: 11.6,
    clearanceNormalMm: 12.2,
    clearanceFreeMm: 12.8,
    minorDiaMm: 9.144,
  },
  {
    id: "unc-1-2-13",
    system: "unc",
    designation: "½-13 UNC",
    majorDiaMm: 12.7,
    majorDiaIn: 0.5,
    pitchMm: null,
    tpi: 13,
    tapDrillMm: 10.7,
    tapDrillIn: "27/64″",
    clearanceCloseMm: 13.5,
    clearanceNormalMm: 14.0,
    clearanceFreeMm: 14.5,
    minorDiaMm: 10.592,
  },
  {
    id: "unc-9-16-12",
    system: "unc",
    designation: "9/16-12 UNC",
    majorDiaMm: 14.288,
    majorDiaIn: 0.563,
    pitchMm: null,
    tpi: 12,
    tapDrillMm: 12.1,
    tapDrillIn: "15/32″",
    clearanceCloseMm: 15.0,
    clearanceNormalMm: 15.5,
    clearanceFreeMm: 16.5,
    minorDiaMm: 11.989,
  },
  {
    id: "unc-5-8-11",
    system: "unc",
    designation: "⅝-11 UNC",
    majorDiaMm: 15.875,
    majorDiaIn: 0.625,
    pitchMm: null,
    tpi: 11,
    tapDrillMm: 13.5,
    tapDrillIn: "17/32″",
    clearanceCloseMm: 16.5,
    clearanceNormalMm: 17.5,
    clearanceFreeMm: 18.5,
    minorDiaMm: 13.386,
  },
  {
    id: "unc-3-4-10",
    system: "unc",
    designation: "¾-10 UNC",
    majorDiaMm: 19.05,
    majorDiaIn: 0.75,
    pitchMm: null,
    tpi: 10,
    tapDrillMm: 16.5,
    tapDrillIn: "21/32″",
    clearanceCloseMm: 20.0,
    clearanceNormalMm: 21.0,
    clearanceFreeMm: 22.0,
    minorDiaMm: 16.307,
  },
  {
    id: "unc-7-8-9",
    system: "unc",
    designation: "⅞-9 UNC",
    majorDiaMm: 22.225,
    majorDiaIn: 0.875,
    pitchMm: null,
    tpi: 9,
    tapDrillMm: 19.4,
    tapDrillIn: "49/64″",
    clearanceCloseMm: 23.0,
    clearanceNormalMm: 24.0,
    clearanceFreeMm: 26.0,
    minorDiaMm: 19.169,
  },
  {
    id: "unc-1-8",
    system: "unc",
    designation: "1″-8 UNC",
    majorDiaMm: 25.4,
    majorDiaIn: 1.0,
    pitchMm: null,
    tpi: 8,
    tapDrillMm: 22.2,
    tapDrillIn: "7/8″",
    clearanceCloseMm: 26.0,
    clearanceNormalMm: 28.0,
    clearanceFreeMm: 30.0,
    minorDiaMm: 21.971,
  },
];

/* ------------------------------------------------------------------ */
/*  UNF (Unified National Fine)                                        */
/* ------------------------------------------------------------------ */
const UNF: TapDrillEntry[] = [
  {
    id: "unf-4-48",
    system: "unf",
    designation: "#4-48 UNF",
    majorDiaMm: 2.845,
    majorDiaIn: 0.112,
    pitchMm: null,
    tpi: 48,
    tapDrillMm: 2.4,
    tapDrillIn: "#41",
    clearanceCloseMm: 3.0,
    clearanceNormalMm: 3.2,
    clearanceFreeMm: 3.4,
    minorDiaMm: 2.271,
  },
  {
    id: "unf-6-40",
    system: "unf",
    designation: "#6-40 UNF",
    majorDiaMm: 3.505,
    majorDiaIn: 0.138,
    pitchMm: null,
    tpi: 40,
    tapDrillMm: 2.95,
    tapDrillIn: "#33",
    clearanceCloseMm: 3.7,
    clearanceNormalMm: 3.9,
    clearanceFreeMm: 4.2,
    minorDiaMm: 2.819,
  },
  {
    id: "unf-8-36",
    system: "unf",
    designation: "#8-36 UNF",
    majorDiaMm: 4.166,
    majorDiaIn: 0.164,
    pitchMm: null,
    tpi: 36,
    tapDrillMm: 3.6,
    tapDrillIn: "#29",
    clearanceCloseMm: 4.3,
    clearanceNormalMm: 4.5,
    clearanceFreeMm: 4.8,
    minorDiaMm: 3.404,
  },
  {
    id: "unf-10-32",
    system: "unf",
    designation: "#10-32 UNF",
    majorDiaMm: 4.826,
    majorDiaIn: 0.19,
    pitchMm: null,
    tpi: 32,
    tapDrillMm: 4.1,
    tapDrillIn: "#21",
    clearanceCloseMm: 5.0,
    clearanceNormalMm: 5.2,
    clearanceFreeMm: 5.5,
    minorDiaMm: 4.064,
  },
  {
    id: "unf-1-4-28",
    system: "unf",
    designation: "¼-28 UNF",
    majorDiaMm: 6.35,
    majorDiaIn: 0.25,
    pitchMm: null,
    tpi: 28,
    tapDrillMm: 5.5,
    tapDrillIn: "#3",
    clearanceCloseMm: 6.6,
    clearanceNormalMm: 7.0,
    clearanceFreeMm: 7.4,
    minorDiaMm: 5.359,
  },
  {
    id: "unf-5-16-24",
    system: "unf",
    designation: "5/16-24 UNF",
    majorDiaMm: 7.938,
    majorDiaIn: 0.313,
    pitchMm: null,
    tpi: 24,
    tapDrillMm: 6.9,
    tapDrillIn: "I",
    clearanceCloseMm: 8.2,
    clearanceNormalMm: 8.6,
    clearanceFreeMm: 9.1,
    minorDiaMm: 6.782,
  },
  {
    id: "unf-3-8-24",
    system: "unf",
    designation: "⅜-24 UNF",
    majorDiaMm: 9.525,
    majorDiaIn: 0.375,
    pitchMm: null,
    tpi: 24,
    tapDrillMm: 8.5,
    tapDrillIn: "Q",
    clearanceCloseMm: 9.9,
    clearanceNormalMm: 10.4,
    clearanceFreeMm: 11.0,
    minorDiaMm: 8.379,
  },
  {
    id: "unf-7-16-20",
    system: "unf",
    designation: "7/16-20 UNF",
    majorDiaMm: 11.113,
    majorDiaIn: 0.438,
    pitchMm: null,
    tpi: 20,
    tapDrillMm: 9.9,
    tapDrillIn: "25/64″",
    clearanceCloseMm: 11.6,
    clearanceNormalMm: 12.2,
    clearanceFreeMm: 12.8,
    minorDiaMm: 9.728,
  },
  {
    id: "unf-1-2-20",
    system: "unf",
    designation: "½-20 UNF",
    majorDiaMm: 12.7,
    majorDiaIn: 0.5,
    pitchMm: null,
    tpi: 20,
    tapDrillMm: 11.5,
    tapDrillIn: "29/64″",
    clearanceCloseMm: 13.5,
    clearanceNormalMm: 14.0,
    clearanceFreeMm: 14.5,
    minorDiaMm: 11.326,
  },
  {
    id: "unf-9-16-18",
    system: "unf",
    designation: "9/16-18 UNF",
    majorDiaMm: 14.288,
    majorDiaIn: 0.563,
    pitchMm: null,
    tpi: 18,
    tapDrillMm: 13.0,
    tapDrillIn: "33/64″",
    clearanceCloseMm: 15.0,
    clearanceNormalMm: 15.5,
    clearanceFreeMm: 16.5,
    minorDiaMm: 12.761,
  },
  {
    id: "unf-5-8-18",
    system: "unf",
    designation: "⅝-18 UNF",
    majorDiaMm: 15.875,
    majorDiaIn: 0.625,
    pitchMm: null,
    tpi: 18,
    tapDrillMm: 14.5,
    tapDrillIn: "37/64″",
    clearanceCloseMm: 16.5,
    clearanceNormalMm: 17.5,
    clearanceFreeMm: 18.5,
    minorDiaMm: 14.348,
  },
  {
    id: "unf-3-4-16",
    system: "unf",
    designation: "¾-16 UNF",
    majorDiaMm: 19.05,
    majorDiaIn: 0.75,
    pitchMm: null,
    tpi: 16,
    tapDrillMm: 17.5,
    tapDrillIn: "11/16″",
    clearanceCloseMm: 20.0,
    clearanceNormalMm: 21.0,
    clearanceFreeMm: 22.0,
    minorDiaMm: 17.33,
  },
];

/* ------------------------------------------------------------------ */
/*  NPT (ANSI B1.20.1 taper pipe) — tap drill is the pipe's small end */
/* ------------------------------------------------------------------ */
const NPT: TapDrillEntry[] = [
  {
    id: "npt-1-16-27",
    system: "npt",
    designation: "1/16-27 NPT",
    majorDiaMm: 7.938,
    majorDiaIn: 0.313,
    pitchMm: null,
    tpi: 27,
    tapDrillMm: 6.35,
    tapDrillIn: "C",
    clearanceCloseMm: 6.5,
    clearanceNormalMm: 6.7,
    clearanceFreeMm: 7.0,
    minorDiaMm: null,
  },
  {
    id: "npt-1-8-27",
    system: "npt",
    designation: "⅛-27 NPT",
    majorDiaMm: 10.287,
    majorDiaIn: 0.405,
    pitchMm: null,
    tpi: 27,
    tapDrillMm: 8.7,
    tapDrillIn: "21.9 mm",
    clearanceCloseMm: 10.5,
    clearanceNormalMm: 11.0,
    clearanceFreeMm: 11.5,
    minorDiaMm: null,
  },
  {
    id: "npt-1-4-18",
    system: "npt",
    designation: "¼-18 NPT",
    majorDiaMm: 13.716,
    majorDiaIn: 0.54,
    pitchMm: null,
    tpi: 18,
    tapDrillMm: 11.1,
    tapDrillIn: "7/16″",
    clearanceCloseMm: 14.0,
    clearanceNormalMm: 14.5,
    clearanceFreeMm: 15.2,
    minorDiaMm: null,
  },
  {
    id: "npt-3-8-18",
    system: "npt",
    designation: "⅜-18 NPT",
    majorDiaMm: 17.145,
    majorDiaIn: 0.675,
    pitchMm: null,
    tpi: 18,
    tapDrillMm: 14.5,
    tapDrillIn: "37/64″",
    clearanceCloseMm: 17.5,
    clearanceNormalMm: 18.0,
    clearanceFreeMm: 19.0,
    minorDiaMm: null,
  },
  {
    id: "npt-1-2-14",
    system: "npt",
    designation: "½-14 NPT",
    majorDiaMm: 21.336,
    majorDiaIn: 0.84,
    pitchMm: null,
    tpi: 14,
    tapDrillMm: 17.9,
    tapDrillIn: "23/32″",
    clearanceCloseMm: 21.5,
    clearanceNormalMm: 22.0,
    clearanceFreeMm: 23.0,
    minorDiaMm: null,
  },
  {
    id: "npt-3-4-14",
    system: "npt",
    designation: "¾-14 NPT",
    majorDiaMm: 26.67,
    majorDiaIn: 1.05,
    pitchMm: null,
    tpi: 14,
    tapDrillMm: 23.3,
    tapDrillIn: "15/16″",
    clearanceCloseMm: 27.0,
    clearanceNormalMm: 28.0,
    clearanceFreeMm: 29.0,
    minorDiaMm: null,
  },
  {
    id: "npt-1-11-5",
    system: "npt",
    designation: "1″-11½ NPT",
    majorDiaMm: 33.401,
    majorDiaIn: 1.315,
    pitchMm: null,
    tpi: 11.5,
    tapDrillMm: 29.3,
    tapDrillIn: "1 5/32″",
    clearanceCloseMm: 34.0,
    clearanceNormalMm: 35.0,
    clearanceFreeMm: 36.0,
    minorDiaMm: null,
  },
];

/* ------------------------------------------------------------------ */
/*  BSP (British Standard Pipe, parallel — G thread)                   */
/* ------------------------------------------------------------------ */
const BSP: TapDrillEntry[] = [
  {
    id: "bsp-1-8-28",
    system: "bsp",
    designation: "G⅛ × 28",
    majorDiaMm: 9.728,
    majorDiaIn: 0.383,
    pitchMm: null,
    tpi: 28,
    tapDrillMm: 8.8,
    tapDrillIn: "8.8 mm",
    clearanceCloseMm: 10.0,
    clearanceNormalMm: 10.4,
    clearanceFreeMm: 11.0,
    minorDiaMm: 8.566,
  },
  {
    id: "bsp-1-4-19",
    system: "bsp",
    designation: "G¼ × 19",
    majorDiaMm: 13.157,
    majorDiaIn: 0.518,
    pitchMm: null,
    tpi: 19,
    tapDrillMm: 11.8,
    tapDrillIn: "11.8 mm",
    clearanceCloseMm: 13.5,
    clearanceNormalMm: 14.0,
    clearanceFreeMm: 14.5,
    minorDiaMm: 11.445,
  },
  {
    id: "bsp-3-8-19",
    system: "bsp",
    designation: "G⅜ × 19",
    majorDiaMm: 16.662,
    majorDiaIn: 0.656,
    pitchMm: null,
    tpi: 19,
    tapDrillMm: 15.25,
    tapDrillIn: "15.25 mm",
    clearanceCloseMm: 17.0,
    clearanceNormalMm: 17.5,
    clearanceFreeMm: 18.5,
    minorDiaMm: 14.95,
  },
  {
    id: "bsp-1-2-14",
    system: "bsp",
    designation: "G½ × 14",
    majorDiaMm: 20.955,
    majorDiaIn: 0.825,
    pitchMm: null,
    tpi: 14,
    tapDrillMm: 18.6,
    tapDrillIn: "18.6 mm",
    clearanceCloseMm: 21.5,
    clearanceNormalMm: 22.0,
    clearanceFreeMm: 23.0,
    minorDiaMm: 18.631,
  },
  {
    id: "bsp-3-4-14",
    system: "bsp",
    designation: "G¾ × 14",
    majorDiaMm: 26.441,
    majorDiaIn: 1.041,
    pitchMm: null,
    tpi: 14,
    tapDrillMm: 24.1,
    tapDrillIn: "24 mm",
    clearanceCloseMm: 27.0,
    clearanceNormalMm: 28.0,
    clearanceFreeMm: 29.0,
    minorDiaMm: 24.117,
  },
  {
    id: "bsp-1-11",
    system: "bsp",
    designation: "G1 × 11",
    majorDiaMm: 33.249,
    majorDiaIn: 1.309,
    pitchMm: null,
    tpi: 11,
    tapDrillMm: 30.3,
    tapDrillIn: "30.3 mm",
    clearanceCloseMm: 34.0,
    clearanceNormalMm: 35.0,
    clearanceFreeMm: 36.0,
    minorDiaMm: 30.291,
  },
];

export const TAP_DRILL_ENTRIES: readonly TapDrillEntry[] = Object.freeze([
  ...ISO_COARSE,
  ...ISO_FINE,
  ...UNC,
  ...UNF,
  ...NPT,
  ...BSP,
]);

export const THREAD_SYSTEMS: readonly { id: ThreadSystem; label: string }[] = Object.freeze([
  { id: "iso-coarse", label: "Metric Coarse (M)" },
  { id: "iso-fine", label: "Metric Fine (MF)" },
  { id: "unc", label: "UNC — Unified Coarse" },
  { id: "unf", label: "UNF — Unified Fine" },
  { id: "npt", label: "NPT — Taper Pipe" },
  { id: "bsp", label: "BSP — British Pipe" },
]);
